### ISSUE TITLE
Package Pake (if possible)

### ISSUE THREAD

**Issue by jhheider** [pkgxdev/pantry#121]
WIP: https://github.com/teaxyz/pantry.extra/commit/d42536a4a4926f3de59a4df48b0a2a7c9877f0a0

Currently, it appears that Pake needs x86-64 to cross-compile on aarch64: https://github.com/tw93/Pake/issues/14.

Pull requests to work around this are definitely welcome.

**Comment by mxcl** [comment]
For the curious https://github.com/tw93/Pake
