### ISSUE TITLE
Linux git: `fatal: unable to access 'https://github.com/zyedidia/micro.git/': error setting certificate verify locations:  CAfile: /etc/ssl/certs/ca-certificates.crt CApath: none

### ISSUE THREAD

**Issue by magnusviri** [pkgxdev/pantry#1219]
I think the curl.se/ca-certs is wrong for git (it works for curl).

```
docker run --rm -it teaxyz/cli bash
```

Inside of the container:

```
git clone https://github.com/zyedidia/micro.git
Cloning into 'micro'...
fatal: unable to access 'https://github.com/zyedidia/micro.git/': error setting certificate verify locations:  CAfile: /etc/ssl/certs/ca-certificates.crt CApath: none
```

curl works

```
curl https://tea.xyz
#!/bin/sh

set -e
set -o noglob
...
```

**Comment by magnusviri** [comment]
I should clarify, I'm using macOS to get into Linux by running docker.

**Comment by jhheider** [comment]
There have been some changes to `ca-certs` for `git`: https://github.com/teaxyz/pantry/commit/b010995fb8e4a80dca87eb5ff35265d1f326598b. Can you confirm that content appears in your curl.se/ca-certs/package.yml? If not, you'll likely need to run `tea -S`.

**Comment by jhheider** [comment]
You may need to `--pull` teaxyz/cli if it's older than that commit (to prevent having to run `tea -S` prophylactically.

**Comment by mxcl** [comment]
`tea -S` doesn’t work for pkgs that were updated but didn’t bump. We should fix that though.

**Comment by magnusviri** [comment]
Just retried and there's no error now.
