### ISSUE TITLE
git [warning]

### ISSUE THREAD

**Issue by tnxz** [pkgxdev/pantry#123]
`git clone ...` triggers this (also `gh` as it seem to use `git` under the hood)

shouldn't it be looking in `~/.tea/git-scm.org`
```
warning: templates not found in /opt/git-scm.org/v2.39.0/share/git-core/templates
```

**Comment by jhheider** [comment]
Sure should. Guessing there's a hard-coded path left over from the build. So, the following works:
```sh
GIT_TEMPLATE_DIR=~/.tea/git-scm.org/v2/share/git-core/templates tea git clone https://github.com/rustls/rustls
```

So, if there's no way to make it bin-path dependent, at least there's a runtime environment configuration we can use.

**Comment by jhheider** [comment]
Fix prepared.

**Comment by mxcl** [comment]
Should be fixed in the next build (happening now!) to reinstall and already installed package you currently must `rm -rf ~/.tea/git-scm.org` first unfortunately…
