### ISSUE TITLE
Error: 404: https://dist.tea.xyz/apache.org/apr/darwin/aarch64/versions.txt

### ISSUE THREAD

**Issue by magnusviri** [pkgxdev/pantry#1258]
If I understand correctly, the [apache.org/apr](https://github.com/teaxyz/pantry/blob/main/projects/apache.org/apr/package.yml) recipe should create a darwin/aarch64 version, but [it's missing](https://dist.tea.xyz/?prefix=apache.org/apr/darwin/).

**Comment by jhheider** [comment]
Looks like that merge didn't build only that version. I'll trigger it.

https://github.com/teaxyz/pantry/actions/runs/4440852628/jobs/7795205207

**Comment by jhheider** [comment]
running: https://github.com/teaxyz/pantry/actions/runs/4614573931

**Comment by jhheider** [comment]
Looks like a concurrency build issue. I'll sort it.
