### ISSUE TITLE
Add nodejs.org~16.11.1 to the inventory

### ISSUE THREAD

**Issue by ubmit** [pkgxdev/pantry#1355]
I just tried to install Node version 16.11.1 using tea and face this issue:

```sh
tea -E
resolving package graph
error: not-found: pkg.version (spilt-tea-006)

inventory: 14.20.1, 14.21.0, 14.21.1, 14.21.2, 14.21.3, 16.18.0, 16.18.1, 16.19.0, 16.19.1, 16.20.0, 18.9.1, 18.12.1, 18.13.0, 18.14.0, 18.14.2, 18.15.0, 18.16.0, 19.0.0, 19.0.1, 19.1.0, 19.2.0, 19.3.0, 19.4.0, 19.5.0, 19.6.0, 19.6.1, 19.7.0, 19.8.0, 19.8.1, 19.9.0

we haven’t packaged nodejs.org~16.11.1. but we will… *if* you open a ticket:

    https://github.com/teaxyz/pantry/issues/new
```

**Comment by jhheider** [comment]
I've triggered builds for =16.11.1, ~16.11.1, and ^16.11.1; that should cover expectations for someone looking for 16.11.

**Comment by jhheider** [comment]
It looks like the first two have `gyp` errors on the `--without-corepack` flag (likely require a different build script due to age), but the third (which is building 16.20.0) works fine. So, we'll need to dig into the differences between 2021 and now to see how to build 16.11.x
