### ISSUE TITLE
package +awscli

### ISSUE THREAD

**Issue by getneil** [pkgxdev/pantry#139]
* package `six` first: https://pypi.org/project/six/#files
* then package `awscli`
* ref: https://towardsdatascience.com/how-to-upload-your-python-package-to-pypi-de1b363a1b3

**Comment by getneil** [comment]
or anyone can take this will but will try soon.

**Comment by jhheider** [comment]
https://github.com/teaxyz/pantry.extra/pull/79 is a good starting point.

**Comment by mfts** [comment]
closed by #79
