### ISSUE TITLE
tmux: 3.3a has not been released

### ISSUE THREAD

**Issue by uesyn** [pkgxdev/pantry#1665]
tmux 3.3a is a bug fix release of 3.3, but it has not been released by tea.

**Comment by uesyn** [comment]
If there's anything I can do to release it, please let me know.

**Comment by jhheider** [comment]
Looks like 3.3a was released last June; well before we had `/(\d+\.)*\d+[a-z]?/` support for versions. I've trigged a build now. https://github.com/teaxyz/pantry/actions/runs/4823537544

**Comment by uesyn** [comment]
@jhheider
Thank you for your support 😄 
When the Job is succeeded, I will close this issue!

**Comment by jhheider** [comment]
We need some changes to our version handling for shorter versions like this, but we'll get there.

**Comment by uesyn** [comment]
@jhheider 
I made the PR to support to upload shorter versions like tmux.
https://github.com/teaxyz/brewkit/pull/101

**Comment by jhheider** [comment]
fixed in brewkit 0.27.0
