### ISSUE TITLE
:heavy_plus_sign: lftp

### ISSUE THREAD

**Issue by adriens** [pkgxdev/pantry#1709]
## :toolbox: Build software

> To build from GIT sources, run autogen.sh script to create Makefiles. You will need autoconf, libtool, gettext-devel, automake, gnulib. You can get gnulib using git clone git://git.savannah.gnu.org/gnulib.

## :bookmark_tabs: Resources

- :bookmark: [website](https://lftp.yar.ru/)
- :ninja: Why `lftp` : [dedicated Killercoda scenario](https://killercoda.com/opt-labs/course/devops-tools/lftp-quickstart)
- :octocat: [`lavv17/lftp`](https://github.com/lavv17/lftp)

**Comment by adriens** [comment]
Still I cannot find it : 

![image](https://user-images.githubusercontent.com/5235127/236579762-26c9e6b4-be48-498c-ac33-5f39a9788526.png)

**Comment by jhheider** [comment]
upload had a 500 for darwin+x86-64: https://github.com/teaxyz/pantry/actions/runs/4898087904. It's showing up in the gui now for me (though I don't know what the refresh schedule is; if it requires reloading the window or reopening the app to trigger, we should talk to the @teaxyz/gui team about it).

**Comment by adriens** [comment]
Ok, i'll test it later this we :crossed_fingers:

**Comment by jhheider** [comment]
i think the issue might be f6f7b1c89d395828402c3e1ff22effa8546380c7; to that end, i've triggered the [`new-version` action](https://github.com/teaxyz/pantry/actions/runs/4898426845), which _does_ end with an indexing. it should complete soon.

**Comment by adriens** [comment]
[YUP it actually did :clap: ](https://tea.xyz/+lftp.yar.ru/)

![image](https://user-images.githubusercontent.com/5235127/236587742-aa36f5bb-7a99-4394-8e49-41e21438a2a6.png)


![image](https://user-images.githubusercontent.com/5235127/236587757-31ee9d1e-3876-4586-9683-3900e9c73886.png)
