### ISSUE TITLE
Broken Link in Wiki

### ISSUE THREAD

**Issue by jacob-willden** [pkgxdev/pantry#2145]
In [the "Editing your pkg section" of the Home page of this repository's wiki](https://github.com/teaxyz/pantry/wiki#editing-your-pkg), the "Structure of a pkg" link just redirects to the Home page, with the following error message: "You do not have permission to update this wiki." 

The link needs to be updated from "https://github.com/teaxyz/pantry/wiki/Structure-of-a-package.yml" to "https://github.com/teaxyz/pantry/wiki/Structure-of-a-%60package.yml%60" (`%60` is the URL-encoded back-tick).

**Comment by mxcl** [comment]
Fixed. Thank you. Feel free to edit yourself next time! The wiki is community owned.

**Comment by jacob-willden** [comment]
Oh good to know! Thanks!
