### ISSUE TITLE
Python.h missing in some of the python versions

### ISSUE THREAD

**Issue by magnusviri** [pkgxdev/pantry#2147]
These are the pythons that I have installed. I've indicated which ones are missing Python.h.

```
/opt/tea/python.org/v3.7.16/include/python3.7m/Python.h
/opt/tea/python.org/v3.8.16/include/python3.8/Python.h
/opt/tea/python.org/v3.9.16/include/python3.9/Python.h
/opt/tea/python.org/v3.10.8/include/python3.10/Python.h
/opt/tea/python.org/v3.10.11 <-missing
/opt/tea/python.org/v3.11.0/include/python3.11/Python.h
/opt/tea/python.org/v3.11.1/include/python3.11/Python.h
/opt/tea/python.org/v3.11.2/include/python3.11/Python.h
/opt/tea/python.org/v3.11.3 <-missing
```

**Comment by magnusviri** [comment]
I am so confused. I've been doing stuff and now they are there. I think the package I've been trying to build (cython) fixed this problem. I'm going to close this because I don't really know if this is an issue or not. If I find out it is a real issue, I'll re-open.

**Comment by mxcl** [comment]
for your sanity I can confirm these versions *do* have Python.h. However possibly older instances of these bottles did not or something.
