### ISSUE TITLE
Jupyter 4.x is missing jupyter-notebook

### ISSUE THREAD

**Issue by magnusviri** [pkgxdev/pantry#2265]
This works: `tea jupyter=3.6.4 notebook`. This doesn't work: 

```
tea jupyter=4.0.2 notebook
/opt/tea/jupyter.org/v4.0.2/bin/jupyter-notebook: line 22: /opt/tea/jupyter.org/v4.0.2/venv/bin/jupyter-notebook: No such file or directory
/opt/tea/jupyter.org/v4.0.2/bin/jupyter-notebook: line 22: exec: /opt/tea/jupyter.org/v4.0.2/venv/bin/jupyter-notebook: cannot execute: No such file or directory
```

Here's the releases: https://github.com/jupyterlab/jupyterlab/releases

I'm not sure what changed, but somehow the newer version is missing v*/venv/bin/jupyter-notebook.

I've got to say, I just installed 4 different versions of jupyter to test this, and this is slicker than anything.

**Comment by jhheider** [comment]
Probably needs to be rebuilt after https://github.com/teaxyz/brewkit/pull/142. I'll trigger that now.

https://github.com/teaxyz/pantry/actions/runs/5341661892

If that's not the fix, then likely something changed in the layout with 4.x.

**Comment by magnusviri** [comment]
Just tried this (version 4.0.8) and it's still a problem.

**Comment by magnusviri** [comment]
I think jupyter-notebook has been removed in version 4. It's replaced with jupyter-lab. I've been trying to find an official comment on it, but I can't find anything yet.

**Comment by magnusviri** [comment]
So I installed jupyterlab normally and it didn't include notebook. Homebrew's jupyterlab does include it, and I think that's because they [added it purposely](https://github.com/Homebrew/homebrew-core/blob/5373def163f8fdcba579a3febe1978c1849d56b6/Formula/j/jupyterlab.rb#L380). So this isn't a bug, it's a decision. I haven't really used Jupyter Notebook or Jupyterlab. Notebook is supposed to be simpler and easier, but I've gotten the impression that most people prefer Jupyterlab.

Right now the jupyterlab package.yml file installs a shim for jupyter-notebook. So it either needs to be removed or the jupyterlab package.yml file should be modified to install notebook (`pip install notebook`).
