### ISSUE TITLE
Include clang sanitizers

### ISSUE THREAD

**Issue by zack-alex** [pkgxdev/pantry#2294]
Hello!

Apparently, the clang from tea doesn't have sanitizer runtime libraries:
```
% clang -fsanitize=address,undefined hello.c
ld: file not found: /Users/zahaaar/.tea/llvm.org/v16.0.5/lib/clang/16/lib/darwin/libclang_rt.asan_osx_dynamic.dylib
clang-16: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by jhheider** [comment]
My research suggests that's simply including `-DLLVM_ENABLE_RUNTIMES='compiler-rt'` in the build; testing now.

**Comment by jhheider** [comment]
Should be live in 16.0.6; rebuilding ^12, ^13, ^14, and ^15 now.

**Comment by jhheider** [comment]
It looks like maybe ^12 and ^13 don't like being compiled with apple's clang 14 on darwin+aarch64; I'm probably ok with that, for now.

**Comment by zack-alex** [comment]
Works for me now. Thanks!
