### ISSUE TITLE
llvm.org error

### ISSUE THREAD

**Issue by tnxz** [pkgxdev/pantry#2367]
Discussed in https://github.com/orgs/teaxyz/discussions/307
```
$ tea +llvm.org +tea.xyz/gx/cc
$ cc main.c

xcode-select: note: No developer tools were found, requesting install.
If developer tools are located at a non-default location on disk, use `sudo xcode-select --switch path/to/Xcode.app` to specify the Xcode that you wish to use for command line developer tools, and cancel the installation dialog.
See `man xcode-select` for more details.
```

**Comment by jhheider** [comment]
https://github.com/teaxyz/pantry/blob/d39668152e68537017a535597d281a543ce2e634/projects/tea.xyz/gx/cc/package.yml#L8-L12

`tea.xyz/gx/cc` requires CLT. If you just want llvm, you can use it as `llvm.org` as you have it without cc.

**Comment by tnxz** [comment]
can you give me some pointers on why `cc` need CLT as a dependency

**Comment by jhheider** [comment]
I believe apple's version of clang contains some platform specific code, as well as providing the Macos.sdk, which has the standard library. It is generally considered proper to use apple's compiler on their system, though you always have the option to do otherwise.
