### ISSUE TITLE
+speedtest

### ISSUE THREAD

**Issue by davdroman** [pkgxdev/pantry#2575]
There's no open source repo for this one, only precompiled binaries available on their website: https://www.speedtest.net/apps/cli

Here's the Homebrew formula for it: https://github.com/teamookla/homebrew-speedtest/blob/master/speedtest.rb

I think the only way to derive the version would be to scrape the website's HTML and look for the download links in the shapes of:

- https://install.speedtest.net/app/cli/ookla-speedtest-{version}-macosx-universal.tgz
- https://install.speedtest.net/app/cli/ookla-speedtest-{version}-linux-x86_64.tgz
- https://install.speedtest.net/app/cli/ookla-speedtest-{version}-linux-aarch64.tgz

Probably not the easiest one. Also not sure the package manifest allows parsing versions from raw HTML.

Is this feasable @mxcl?

**Comment by jhheider** [comment]
That looks like a private tap, only supporting macOS. We have the (Apache-2.0 licensed) `github.com/sivel/speedtest-cli` packaged presently; do we have any idea what the source license is for Ookla's binary?

**Comment by jhheider** [comment]
I'm guessing this the source is not openly licensed for use based on:

## TERMS OF USE AND PRIVACY POLICY NOTICES
You may only use this Speedtest software and information generated from it for personal, non-commercial use,
through a command line interface on a personal computer.  Your use of this software is subject to the End User
License Agreement, Terms of Use and Privacy Policy at these URLs:

* [https://www.speedtest.net/about/eula](https://www.speedtest.net/about/eula)
* [https://www.speedtest.net/about/terms](https://www.speedtest.net/about/terms)
* [https://www.speedtest.net/about/privacy](https://www.speedtest.net/about/privacy)

**Comment by davdroman** [comment]
Fair point about the license. Closing.

**Comment by mxcl** [comment]
yeah they pkg it themselves via a tap and licensed it so only they can.

we’ll have a tap like feature at some point this quarter.
