### ISSUE TITLE
Can we delete renamed `RobotsAndPencils/xcodes` bottle?

### ISSUE THREAD

**Issue by davdroman** [pkgxdev/pantry#2615]
<img width="579" alt="image" src="https://github.com/teaxyz/pantry/assets/2538074/247cf877-7988-46e4-ae86-7ea558897cdf">

... as a result of #2313 (sorry).

Can we delete the old `github.com/RobotsAndPencils/xcodes` bottle?

**Comment by jhheider** [comment]
Deleted the bottle. If your pantry still has it, `tea -S` should fix that. If your `TEA_PANTRY_PATH` (likely checkout of teaxyz/pantry) still has it, then rebase onto `main` should clear that out.

@ABevier can we ensure this is cleared out of the pipeline for the gui/web tools?
