### ISSUE TITLE
Using tea's zsh as the default shell

### ISSUE THREAD

**Issue by magnusviri** [pkgxdev/pantry#2628]
I don't think this is an issue you can do anything about, but if I link to tea and name it zsh, the path gets all messed up. I have to link directly to the zsh binary. I just wanted to mention it.

**Comment by jhheider** [comment]
Hm. I wonder if that has to do with this: https://github.com/teaxyz/pantry/blob/962b552b590301b4a59549f55289e5278de512d7/projects/zsh.sourceforge.io/package.yml#L20-L23

I can definitely see shell loops like that getting... messy. `zsh` has some complexity about what it will and won't load externally, which made fixing the MODULE_PATH difficult (see: https://github.com/teaxyz/pantry/blob/962b552b590301b4a59549f55289e5278de512d7/projects/zsh.sourceforge.io/package.yml#L30-L35).

I'll take a look at this. I assume your use-case is system-wide `zsh` link?

**Comment by magnusviri** [comment]
I set it as my user shell (like in the /etc/passwd file, except on macOS).

I don't think you need to fix it. If anything, you could have a FAQ that says to not do it. Or if you wanted, tea could detect if it has an empty PATH and if it does, warn about it.

And maybe there is more to this. If I set my system shell directly to tea's zsh, the PATH works now, but the delete key doesn't! I wonder what that could be about.

**Comment by jhheider** [comment]
@magnusviri this might be worth taking another look at. since `tea install zsh` will create a shim rather than a simple symlink, all our `runtime.env` keys should work. i think.

**Comment by magnusviri** [comment]
Looks like it's working. I'll close this and re-open if I have trouble.
