### ISSUE TITLE
Add dotnet

### ISSUE THREAD

**Issue by marcinjahn** [pkgxdev/pantry#2644]
Having [dotnet](https://dotnet.microsoft.com/en-us/) available via Pantry would be awesome.

**Comment by mxcl** [comment]
* https://dotnet.microsoft.com/en-us/download#macos
* https://formulae.brew.sh/cask/dotnet (cask)
* https://ports.macports.org/port/dotnet-sdk-3.1/details/

So, macports have it and they don't install outside prefix so that means we can do it. Probs.

I agree this would be a great addition. @ArionThinker care to have a lookie?

**Comment by and-ri** [comment]
Sure, I will try to package it :ok_hand:

**Comment by marcinjahn** [comment]
@ArionThinker I see that Linux support requires icu. Is it problematic to enable that?

**Comment by and-ri** [comment]
> @ArionThinker I see that Linux support requires icu. Is it problematic to enable that?

Oh no, it's not probematic. I'll just enable linux support as soon as I package the icu for the pantry

**Comment by marcinjahn** [comment]
> > @ArionThinker I see that Linux support requires icu. Is it problematic to enable that?
> 
> Oh no, it's not probematic. I'll just enable linux support as soon as I package the icu for the pantry

Got it, thanks. How did you know what are the exact dependencies for the linux/Mac versions of the dotnet sdk, like the icu thing?

**Comment by and-ri** [comment]
> > > @ArionThinker I see that Linux support requires icu. Is it problematic to enable that?
> 
> > 
> 
> > Oh no, it's not probematic. I'll just enable linux support as soon as I package the icu for the pantry
> 
> 
> 
> Got it, thanks. How did you know what are the exact dependencies for the linux/Mac versions of the dotnet sdk, like the icu thing?

You can see that in action log: https://github.com/teaxyz/pantry/actions/runs/5656620132/job/15324228581#step:8:1

**Comment by and-ri** [comment]
`Process terminated. Couldn't find a valid ICU package installed on the system. Please install libicu (or icu-libs) using your package manager and try again. Alternatively you can set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support. Please see https://aka.ms/dotnet-missing-libicu for more information.`

**Comment by marcinjahn** [comment]
Thanks 🙂
