### ISSUE TITLE
+docker (333/548)

### ISSUE THREAD

**Issue by mfts** [pkgxdev/pantry#277]
Formulae: https://formulae.brew.sh/formula/docker

**Comment by mxcl** [comment]
So what I want to know is, is this the same as the docker desktop application? Can people use this instead?

As I would jump at dropping the GUI if so.

**Comment by jhheider** [comment]
I believe it's the command-line only; the docker cask is required for the daemon.

https://github.com/docker/cli

AFAIK, Docker Desktop is required on Mac and Windows.

**Comment by jhheider** [comment]
The supposed non-desktop alternative is https://podman.io/, which will require packaging `qemu` (I believe Docker would as well), which is mildly complicated due to its low-levelity.

**Comment by mxcl** [comment]
The fact docker don’t provide a cli only open source solution for Mac or Windows makes me want to move away from them entirely.

**Comment by davdroman** [comment]
@mxcl @jhheider I personally use https://github.com/abiosoft/colima in order to avoid Docker Desktop altogether.

**Comment by mxcl** [comment]
k so let’s pkg it, but stub the binaries so that on failure they point people to colima and pkg that too. @ArionThinker
