### ISSUE TITLE
+numpy (255/548)

### ISSUE THREAD

**Issue by mfts** [pkgxdev/pantry#280]
Formulae: https://formulae.brew.sh/formula/numpy

**Comment by ddobrinskiy** [comment]
I'm actually skeptical that this should be a separate package.

Numpy is a Python library, and it is a well known fact in python community that you should only install python packages via virtualenv/conda/mamba or some other env management tool.

Also numpy is not some kind of python-based CLI tool that would make sense to use from the terminal if we installed it via virtualenv.

This actually surprises me that numpy is in top300, but anyway we should not let people shoot themselves in the foot here

**Comment by mfts** [comment]
I tend to agree with you on that one. I simply added it for completeness because it appeared in the top 300 packages that users install via homebrew. 

I'm not sure where outside of python programs you'd use this one.

**Comment by ddobrinskiy** [comment]
> I'm not sure where outside of python programs you'd use this one.

You wouldn't, numpy does not have a CLI interface - it can only be used as part of other python programs.

And the [homebrew formulae](https://formulae.brew.sh/formula/numpy) installs it into base python env, which should be a criminal offence IMHO :laughing:

**Comment by mxcl** [comment]
Closing due to the above excellent rationale.

Let’s copy brew’s mistakes blindly.
