### ISSUE TITLE
+man

### ISSUE THREAD

**Issue by mxcl** [pkgxdev/pantry#2980]
We need `man` for various reasons.

* there's https://man-db.gitlab.io/man-db/
* but I wonder what the `man` that eg. macOS pkgs is? I cannot find it. The above is newer and has more deps and more deps is tedious.

**Comment by mxcl** [comment]
@ArionThinker can you add this pls

**Comment by and-ri** [comment]
> @ArionThinker can you add this pls

Sure, I'll do it 👌🏻
