### ISSUE TITLE
Corepack

### ISSUE THREAD

**Issue by GauBen** [pkgxdev/pantry#2996]
[Corepack](https://github.com/nodejs/corepack) is Node.js's attempt at auto-installing package managers

As of now, corepack is not included in [nodejs.org package.yml](https://github.com/teaxyz/pantry/blob/main/projects/nodejs.org/package.yml), despite being advertised as [shipped with node 14 and 16+](https://nodejs.org/api/corepack.html#corepack)

Does corepack make sense with tea? How should the two get along?

Here is how I would love things to work:

### Contributing to a repo using corepack

* Install/upgrade tea
* `git clone repo && cd repo`
* `yarn/pnpm install` which uses corepack to install the right package manager, and throws an error if the wrong pm is used

### Creating a new project

* Install/upgrade tea
* `git init repo && cd repo`
* `echo 20>.node-version`
* `yarn init -2` (which will write `{"packageManager":"yarn@..."}` in package.json)
* All calls to `yarn` will pass through corepack, first one using a [known good release](https://github.com/nodejs/corepack#known-good-releases), next ones with the exact version specified in package.json

I would love to contribute to tea

**Comment by jhheider** [comment]
We should definitely ship it, if people are using it. Is it versioned with nodejs, or separately (like npm)? That would determine whether it should be its own package or not.

**Comment by GauBen** [comment]
Corepack is currently packaged separately from Node, but the [Envisioned workflow](https://github.com/nodejs/corepack/blob/main/DESIGN.md#envisioned-workflow) mentions corepack distributed as a node subcommand:

> Corepack could potentially be distributed as a Node subcommand rather than a standalone binary. In this case, commands in this document (such as corepack install <name@version>) would be replaced by `node --corepack install <name@version>` (or any other variant).

We might want to future-proof tea's node distribution by already including corepack

**Comment by jhheider** [comment]
if it's a) purely additive, and b) not independently versioned, then we should ship it with nodejs. if it's independently versioned (like npm) then we should ship it separately, and figure out how to integrate it.

**Comment by GauBen** [comment]
An additional concern is that both the yarn package and the corepack package would be competing for the `yarn` binary (same for pnpm)

**Comment by jhheider** [comment]
Currently, tea magic tells you when a command is ambiguous and guides you to be explicit. While annoying, this would work with that. Otherwise, you'd just explicitly set your versions in your dev environment.

**Comment by GauBen** [comment]
I've been thinking about it, tea users don't need corepack (at least for development) because tea is corepack (somewhat). Adding support for `package.json#packageManager` ([node doc](https://nodejs.org/api/packages.html#packagemanager), [corepack doc](https://github.com/nodejs/corepack#when-authoring-packages)) should be enough for most users.

Thanks for your quick answers at all times [jhheider](https://github.com/jhheider)!

Edit: I usually use yarn > 2, which stores itself in `.yarn/release`, with a global yarn 1 install (installed with [volta](https://volta.sh/) and which takes care of calling the local yarn release if available). I look forward not having to store a yarn release in all projects, as it seems to be the way yarn 4 is taking.

**Comment by GauBen** [comment]
Thanks!
