### ISSUE TITLE
+caddy

### ISSUE THREAD

**Issue by chrisbbreuer** [pkgxdev/pantry#2999]
I just started thinking about which reverse proxy to use for Stacks.js to create "pretty domains" as local development URLs. _i.e. instead of using `http://localhost:3333`, we would like to use a dynamic `https://$appUrl.test` for the users' applications._

nginx is a valid option that would be usable right now but I am appeased by caddy's modern simplicity, so I figured I'd check the tea pantry if it's available yet. And since I didn't see it covered anywhere, I thought to might as well create this ticket 🙏🏽

The brew formula is here: https://formulae.brew.sh/formula/caddy

**Comment by jhheider** [comment]
Looks like straightforward `go` build. shouldn't be hard.
