### ISSUE TITLE
+sqlfluff.com

### ISSUE THREAD

**Issue by kevinmichaelchen** [pkgxdev/pantry#3004]
sql linter formatter

https://docs.sqlfluff.com/en/stable/

**Comment by kevinmichaelchen** [comment]
@jhheider  - do you know of any notable `pantry` examples of packaging up python projects into static binaries?

**Comment by jhheider** [comment]
Do I ever. aws-cli is probably the biggest, but if you search for `python-venv`, there's both a shell script and a python script (which should work reasonably similarly. i think.) for packaging python venvs for `tea`. bonus points if you want to read the scripts (in teaxyz/brewkit) to see what they're doing.

**Comment by kevinmichaelchen** [comment]
huzzah!

https://github.com/teaxyz/pantry/pull/3325

**Comment by jhheider** [comment]
I like when it's easy.
