### ISSUE TITLE
+telnet (548/548)

### ISSUE THREAD

**Issue by mfts** [pkgxdev/pantry#309]
Formulae: https://formulae.brew.sh/formula/telnet

**Comment by magnusviri** [comment]
I'm working on this. https://github.com/teaxyz/pantry/pull/825

**Comment by magnusviri** [comment]
Do we care if this is Apple's version or not? I'm guessing the Apple version will only work on macOS and not Linux. I'm working on the gnu versions and I'm wondering if that can just be good enough. https://github.com/teaxyz/pantry/pull/860

**Comment by jhheider** [comment]
I'm guessing Apple's version is BSD[citation needed]. GNU version is in inettools, right? That's likely a fine satisfaction. The great thing about our namespacing is we can have both.

**Comment by magnusviri** [comment]
So do you want to leave this open for the BSD version?

**Comment by jhheider** [comment]
If you're interested, sure.

**Comment by magnusviri** [comment]
I'm not. I don't care what version of telnet I have. I just need any version. I obviously can't speak for anyone else. I don't know what other people do.

**Comment by jhheider** [comment]
^. I'd say close it then. No need to package software you're not interested in, unless you become really, _really_ bored.

**Comment by magnusviri** [comment]
I am not bored. https://koe.ai/

**Comment by magnusviri** [comment]
This can be closed.
