### ISSUE TITLE
+emacs (296/548)

### ISSUE THREAD

**Issue by mfts** [pkgxdev/pantry#336]
Formulae: https://formulae.brew.sh/formula/emacs

**Comment by getneil** [comment]
this needs https://github.com/teaxyz/pantry.extra/issues/334

**Comment by ghost** [comment]
Hi @getneil, I'm checking out tea and Emacs was one of the first packages I looked for and found this issue. I might take a stab at it packaging it up in tea, though it wasn't clear to me why `jansson` is a requirement. 

AFAIK upstream Emacs dependencies do not include that package. I was also unable to find an explanation for why it was added as a dependency to the brew package. Please let me know if I'm missing something!

**Comment by getneil** [comment]
> Hi @getneil, I'm checking out tea and Emacs was one of the first packages I looked for and found this issue. I might take a stab at it packaging it up in tea, though it wasn't clear to me why `jansson` is a requirement.
> 
> AFAIK upstream Emacs dependencies do not include that package. I was also unable to find an explanation for why it was added as a dependency to the brew package. Please let me know if I'm missing something!

I also have no idea why it's a requirement. please go ahead.

**Comment by getneil** [comment]
@Borlaag i tried packaging. there is an existing PR atm here https://github.com/teaxyz/pantry/pull/827
