### ISSUE TITLE
+which

### ISSUE THREAD

**Issue by mxcl** [pkgxdev/pantry#3443]
we need `which`. I'm surprised we don't have it @ArionThinker

**Comment by jhheider** [comment]
https://github.com/Homebrew/homebrew-core/blob/34d4f465659c1813ae1c2063991513df072bf089/Formula/g/gnu-which.rb

**Comment by jhheider** [comment]
https://github.com/teaxyz/pantry/commit/62ff4dc4ae16c3368bb9cba7b6cb867cb9eb55c1

**Comment by and-ri** [comment]
> [62ff4dc](https://github.com/teaxyz/pantry/commit/62ff4dc4ae16c3368bb9cba7b6cb867cb9eb55c1)

😃 I started doing it too

**Comment by jhheider** [comment]
it was _really_ fast

**Comment by mxcl** [comment]
thank you both
