### ISSUE TITLE
Please add https://tea.xyz/+/ as project URL

### ISSUE THREAD

**Issue by felipecrs** [pkgxdev/pantry#3459]
So that it can be navigated easily. By project URL I mean this:

![image](https://github.com/teaxyz/pantry/assets/29582865/10265c98-7909-4696-a61e-4640c0b45462)

**Comment by felipecrs** [comment]
The URL must have changed now, and I cannot find the new one.

**Comment by jhheider** [comment]
https://pkgx.sh/. I can change it.

**Comment by felipecrs** [comment]
Hm... but I meant the URL which can be used to search for packages like the previous `https://tea.xyz/+/`.

**Comment by jhheider** [comment]
That'll be back. Just needs updating for the new site. ;)

**Comment by mxcl** [comment]
Yeah I'm hoping I'll finish this week. and yes good idea!

I'll make it dist.pkgx.dev for now

**Comment by mxcl** [comment]
set to https://pkgx.dev/pkgs/ a while back now.
