### ISSUE TITLE
ModuleNotFoundError: No module named 'yt_dlp'

### ISSUE THREAD

**Issue by magnusviri** [pkgxdev/pantry#3514]
I started over with a clean environment and now yt-dlp doesn't work.

```
yt-dlp "..."
 ✓  /opt/pkgx/yt-dlp.org/v2023.9.24
Traceback (most recent call last):
  File "/opt/pkgx/yt-dlp.org/v2023.9.24/venv/bin/yt-dlp", line 5, in <module>
    from yt_dlp import main
ModuleNotFoundError: No module named 'yt_dlp'
```

**Comment by jhheider** [comment]
Yeah, a lot of stuff isn't python3.12 ready yet. 587441621e2d68f35349380e69a8b253f7164f3c should have fixed it. try a quick `pkgx --sync` and see if that helps.

**Comment by magnusviri** [comment]
Yay! It worked.

**Comment by jhheider** [comment]
There's a cost to be paid for rapid packaging. We had a similar problem with llvm15 breaking everything on release.
