### ISSUE TITLE
Gem native extension errors on Ruby 3.1.3

### ISSUE THREAD

**Issue by sporkd** [pkgxdev/pantry#3516]
I am having issues building gem native extensions on Ruby v3.1.3. I've traced the issue down to rubygems not being available inside the gem's `extconf.rb`.

Causing the following error [on line 30 of extconf.rb](https://github.com/sass/sassc-ruby/blob/master/ext/extconf.rb#L30) when it hits `Gem::Platform`, but rubygems is not loaded.

Failing here: https://github.com/sass/sassc-ruby/blob/master/ext/extconf.rb#L30

```ruby
Installing sassc 2.4.0 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/peter/code/ruby313_test/vendor/bundle/ruby/3.1.0/gems/sassc-2.4.0/ext
/Users/peter/.pkgx/ruby-lang.org/v3.1.3/bin/ruby -I/Users/peter/.pkgx/rubygems.org/v3.4.20/lib extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.
``` 

I'm not sure what the root cause is in `pkgx`, but I suspect it might have to do with the following comment:
https://github.com/pkgxdev/pantry/blob/main/projects/ruby-lang.org/package.yml#L50-L55

I've also tested on Ruby v3.2.2 and it doesn't have the same issue.

I've attached [ruby313_test.tar.gz](https://github.com/pkgxdev/pantry/files/12795185/ruby313_test.tar.gz) with a `.ruby-version` and `Gemfile` that demonstrates the bug.

```
$ tar xzvf ruby313_test.tar.gz
$ cd ruby313_test
$ dev
$ bundle
```

**Comment by jhheider** [comment]
It's possibly there's been changes to the package.yml that weren't captured when our ruby-lang.org=3.1.3 bottle was built. I'll trigger a rebuild, in case that's at issue.

**Comment by sporkd** [comment]
Thanks for your fast reply @jhheider. Not sure how long it takes for new builds to be available, but I just blew away my `~/.pkgx` dir and tried again. But still getting the same error.

**Comment by jhheider** [comment]
3.1 rebuild failed, so I'm trying some stuff. ;)

**Comment by jhheider** [comment]
`mkmf.rb can't find header files for ruby at /Users/jacob/.pkgx/ruby-lang.org/v3.1.3/lib/ruby/include/ruby.h`

That's a weird path. ruby.h is as /include/ under the package. we can symlink it, certainly.

<some time later>

symlinking solves that issue, but the next one is:
```
current directory: /Users/jacob/foo/ruby313_test/vendor/bundle/ruby/3.1.0/gems/ffi-1.16.2/ext/ffi_c
make DESTDIR\= sitearchdir\=./.gem.20231003-58133-gw3bup sitelibdir\=./.gem.20231003-58133-gw3bup
make: *** No rule to make target `/include/arm64-darwin21/ruby/config.h', needed by `AbstractMemory.o'.  Stop.
```
so, it's looking in weird places for headers. i'll noodle about that.

**Comment by sporkd** [comment]
@jhheider Ah, you want to run `bundle config set --local build.ffi --enable-libffi-alloc` in your project dir. Or replace `--local` with `--global` if you want it everwhere.

**Comment by jhheider** [comment]
It's still looking for config.h in a system-specific path.

**Comment by jhheider** [comment]
if you want to try the fix, `ln -s ../../include ~/.pkgx/ruby-lang.org/v3.1.3/lib/ruby/` will let you try and move forward.

**Comment by sporkd** [comment]
Oh yes, just remembered, I already got past the error you're having by linking in `/opt`:
```
sudo ln -s "$HOME/.pkgx/ruby-lang.org" /opt/ruby-lang.org
```

Slightly different approach. But once you get past that, then you'll get the `extconf.rb` error I'm gettin😉

**Comment by jhheider** [comment]
well, if there's an /opt in the distribution somewhere, we need to work that out for relocatability.

**Comment by jhheider** [comment]
```shell
/Users/jacob/.pkgx/ruby-lang.org/v3.1.3/lib/pkgconfig/ruby-3.1.pc
25:rubyarchprefix=/opt/ruby-lang.org/v3.1.3/lib/ruby
35:rubyhdrdir=/opt/ruby-lang.org/v3.1.3/include
38:rubyarchhdrdir=/opt/ruby-lang.org/v3.1.3/include

/Users/jacob/.pkgx/ruby-lang.org/v3.1.3/lib/ruby/3.1.0/rbconfig.rb
29:  CONFIG["prefix"] = (TOPDIR || DESTDIR + "/opt/ruby-lang.org/v3.1.3")
42:  CONFIG["rubyarchhdrdir"] = "$(DESTDIR)/opt/ruby-lang.org/v3.1.3/include"
45:  CONFIG["rubyhdrdir"] = "$(DESTDIR)/opt/ruby-lang.org/v3.1.3/include"
49:  CONFIG["configure_args"] = " '--prefix=/opt/ruby-lang.org/v3.1.3' '--enable-load-relative' '--disable-rubygems' '--without-gmp' '--with-rubyarchprefix=/opt/ruby-lang.org/v3.1.3/lib/ruby' '--with-rubyhdrdir=/opt/ruby-lang.org/v3.1.3/include' '--with-rubyarchhdrdir=/opt/ruby-lang.org/v3.1.3/include' '--with-vendordir=no' '--with-vendorarchdir=no' '--with-sitedir=no' '--with-sitearchdir=no' '--disable-multiarch' 'CFLAGS=-w ' 'LDFLAGS=-Wl,-rpath,/opt'"
69:  CONFIG["rubyarchprefix"] = "/opt/ruby-lang.org/v3.1.3/lib/ruby"
163:  CONFIG["MJIT_CC"] = "/opt/tea.xyz/gx/cc/v0.1.4/bin/clang"
174:  CONFIG["LDFLAGS"] = "-L. -Wl,-rpath,/opt -fstack-protector-strong -L/opt/gnome.org/libxml2/v2.10.4/lib -L/opt/openssl.org/v1.1.1t/lib -L/opt/pyyaml.org/v0.2.5/lib -L/opt/zlib.net/v1.2.13/lib -L/opt/gnu.org/gettext/v0.21.1/lib"
```
all of these need to be fixed.

**Comment by sporkd** [comment]
Yup, you found what I looked through to come up with that symlink😅. Glad it won't be something I need to keep.

The rbconfig.rb for 3.2 seems more sane, but can't remember if it's also needed there as well.

**Comment by jhheider** [comment]
won't be nothing:
```shell
/Users/jacob/.pkgx/ruby-lang.org/v3.2.2/lib/ruby/3.2.0/rbconfig.rb
29:  CONFIG["prefix"] = (TOPDIR || DESTDIR + "/opt/ruby-lang.org/v3.2.2")
49:  CONFIG["configure_args"] = " '--prefix=/opt/ruby-lang.org/v3.2.2' '--enable-load-relative' '--without-gmp' '--with-rubyarchprefix=/opt/ruby-lang.org/v3.2.2/lib/ruby' '--with-rubyhdrdir=/opt/ruby-lang.org/v3.2.2/include' '--with-rubyarchhdrdir=/opt/ruby-lang.org/v3.2.2/include' '--disable-multiarch' '--with-vendordir=no' '--with-vendorarchdir=no' '--with-sitedir=no' '--with-sitearchdir=no' 'CFLAGS=-w ' 'LDFLAGS=-Wl,-rpath,/opt'"
69:  CONFIG["rubyarchprefix"] = "/opt/ruby-lang.org/v3.2.2/lib/ruby"
170:  CONFIG["MJIT_CC"] = "/opt/tea.xyz/gx/cc/v0.1.6/bin/clang"
```

**Comment by sporkd** [comment]
I may be remembering that `TOPDIR` was being passed in properly in 3.2. Not sure. Still looks like archprefix is hardcoded. etc

**Comment by mxcl** [comment]
I did a fair amount of hacking to get rubygems to be separate from ruby. They claim this is supported but it isn't documented *how*. Perhaps it is not supported.

In general if something is separately versioned then we want to pkg it separately, but we have limits.

I'll take a look into this.

**Comment by sporkd** [comment]
Thanks @mxcl. The weird thing is the references to `Gem` in `extconf.rb` are working in Ruby 3.2.2. So it's almost like it's not separated out in that version, or somehow packaged differently. I tried to diff the directories but can't spot what's different in 3.1.3.

**Comment by gumeson-zipnosis** [comment]
@jhheider @mxcl  So this issue seems seems resolve and I'm now able to build even without the symlink🎉 . I didn't see any PR merged for this. Do you guys know of some other change to pkgx that made is start getting the right prefix?

**Comment by sporkd** [comment]
@jhheider @mxcl So this issue seems resolved and I'm now able to build even without the symlink🎉 . I didn't see any PR merged for this. Do you guys know of some other change to pkgx that made is start getting the right prefix?

**Comment by jhheider** [comment]
Could have to do with changes we made to llvm, gcc, and brewkit having to do with compiler symlinks, but that seems weird.

**Comment by mxcl** [comment]
Closing but this concerns me.

We do delete rubygems from Ruby itself, but maybe we just shouldn't be doing that.

**Comment by adam12** [comment]
~I'm not really sure _why_ it's broken, but could be it as simple as just shipping `lib/ruby` (Ruby headers) in the package?~ EDIT: Looks like the headers are shipped, just in a different location than what Ruby is expecting.

Here's a simple reproducible oneliner. `pkgx +ruby@3.2.1 gem install bcrypt` (bcrypt gem packages it's own C dependencies so it should _just work_ in most circumstances).

EDIT2: And now everything seems to be working correctly, without issue. Very bizarre.

EDIT3: Maybe just an issue with ruby 3.2.1?

```
❯ pkgx +ruby@3.2.1 gem install bcrypt
Building native extensions. This could take a while...
ERROR:  Error installing bcrypt:
        ERROR: Failed to build gem native extension.

    current directory: /Users/adam/.gem/ruby/3.2.0/gems/bcrypt-3.1.20/ext/mri
/Users/adam/.pkgx/ruby-lang.org/v3.2.1/bin/ruby -I/Users/adam/.pkgx/rubygems.org/v3.4.20/lib extconf.rb
mkmf.rb can't find header files for ruby at /Users/adam/.pkgx/ruby-lang.org/v3.2.1/lib/ruby/include/ruby.h

You might have to install separate package for the ruby development
environment, ruby-dev or ruby-devel for example.

extconf failed, exit code 1

Gem files will remain installed in /Users/adam/.gem/ruby/3.2.0/gems/bcrypt-3.1.20 for inspection.
Results logged to /Users/adam/.gem/ruby/3.2.0/extensions/arm64-darwin-21/3.2.0-static/bcrypt-3.1.20/gem_make.out

~
❯ pkgx +ruby@3.2.2 gem install bcrypt
Building native extensions. This could take a while...
Successfully installed bcrypt-3.1.20
Parsing documentation for bcrypt-3.1.20
Done installing documentation for bcrypt after 0 seconds
1 gem installed
```

EDIT4: I tested all the versions on pkgx.dev.

2.7.6 - works
2.7.8 - works
3.0.0 - works
3.0.1 - works
3.0.2 - works
3.0.3 - works
3.0.4 - works
3.0.5 - broken
3.1.0 - works
3.1.1 - works
3.1.2 - broken
3.1.3 - works
3.2.0 - broken
3.2.1 - broken
3.2.2 - works

EDIT5: Comparing the tree of 3.2.1 and 3.2.2, nothing stands out as the reason for the breakage.

EDIT5: Comparing `RbConfig::CONFIG` between 3.2.1 and 3.2.2, I notice that 3.2.1 (broken) refers to `/opt/ruby-lang.org` in a lot of paths,  where as 3.2.2 (working) refers to $HOME/pkgx/ruby-lang.org
