### ISSUE TITLE
Where is pkg command?

### ISSUE THREAD

**Issue by aslafy-z** [pkgxdev/pantry#3554]
While trying to contribute here, I found `pkg` command from https://github.com/pkgxdev/pantry#contributing were not found within a shell with the pkgx shell integration.

Where can I found this command line tool?
Thank you

**Comment by jhheider** [comment]
if you have `pkgx` integrated with your shell (`pkgx integrate`) and run `dev` inside a pkgxdev/pantry checkout, you will have access to the `pkg` command.

**Comment by aslafy-z** [comment]
Yep, I confirm it works. Thank you.

**Comment by mxcl** [comment]
I'll add some text to make this clearer.
