### ISSUE TITLE
Unwanted ncurses and TERMINFO 

### ISSUE THREAD

**Issue by sporkd** [pkgxdev/pantry#3599]
I have a dev project that `pkgx` wants to always install ncurses whenever I cd into it (or run bundle install). I don't see anything in the Gemfile, or other files, that would require ncurses, so that's a bit of a mystery to me. But the problem is I'm using kitty terminal which doesn't use a standard TERM (it uses `xterm-kitty`). And I don't want to be forced to use TMUX for reasons [here](https://sw.kovidgoyal.net/kitty/faq/#i-am-using-tmux-and-have-a-problem) and [here](https://github.com/kovidgoyal/kitty/issues/391#issuecomment-638320745).

But, since ncurses is auto-installed by pkgx, it's trying to use TMUX in the project env, and I get errors when I try to run the project like:
```
Reline::Terminfo::TerminfoError: The terminfo database could not be found.
```

The install of ncurses is also prepending to my TERMINFO env var [here](https://github.com/pkgxdev/pantry/blob/3d623f3f8ef94ffc28aaf513a5fac4fae09debf0/projects/invisible-island.net/ncurses/package.yml#L54), which I suspect may also contribute to the problem🤷‍♂️.

I don't know what the solution should be as I don't fully understand what's happening. But if I can't get it to play nicely with other teminals, I'm hoping there's a way to somehow "prevent" pkgx from installing unwanted dependencies, either in pkgx.yaml, or otherwise. I've tried `env -ncurses`, but it just gets re-added whenever I cd into the directory or run `bundle install`. Any suggestions appreciated!

**Comment by mxcl** [comment]
`git` uses ncurses and if we see `.git` we add git.

So there's a few issues here:

1. you cannot opt out of using `git` with `dev` at this time.
2. you couldn't figure out what was adding ncurses to your environment
3. our ncurses sets TERMINFO and we probs should not be doing that

I think we can help you more immediately by making some easy way to not add git when there is `.git`. Git is often a system dep and it is reasonable that people don't need pkgx to provide it.

We can probs add `PKGX_SOMETHING=git` and have it mean “don't add these deps automatically”.

In the meantime there is no way to fix this beyond `pkgx -ncurses` or `pkgx -git` whenever you step into the directory. Sorry. Will try to get the workaround out in the next few days.

**Comment by sporkd** [comment]
Thanks @mxcl! I can get rid of the error for now by setting my term to `xterm-256color`. Probably not ideal but in case anyone else runs into this. I agree system git is probably a reasonable assumption if the user has a git repo already, but I also understand the vision behind having pkgx install it. Would it make sense to adopt a convention where having a `pkgx.yaml` means only to install what is explicitly defined in the YAML, and ignore auto detecting things like version files and `.git` directory? It could still fall back on that when no `pkgx.yaml` is present...

That would actually solve a few other times where I've had to delete a checked in `.node-version` (for example), because the pantry doesn't have that version and you get the `unexpected error cannot intersect @version` error.  In other words,  presence of `pkgx.yaml` becomes the definition, without having to delete existing version files, which other developers in the repo may still be using. And presence of a `pkgx.yaml` without git would not install git😄 .

**Comment by mxcl** [comment]
> Would it make sense to adopt a convention where having a pkgx.yaml means only to install what is explicitly defined in the YAML, and ignore auto detecting things like version files

Yeah that probably is the right call actually.

Though we should have all node versions and a missing node version shouldn't cause a version intersection error so that's weird. If that happens again pls report it.

**Comment by mxcl** [comment]
It seems to me here if we can patch ncurses so we don’t have to set TERMINFO we fix this issue. Let me take a look.

**Comment by mxcl** [comment]
What system is this? and do you not have a `/usr/share/terminfo` directory?

**Comment by sporkd** [comment]
Thanks for your reply @mxcl. This is OS X. And possibly that report was from before you got node 10.6.0? And no `/usr/share/terminfo`... at lest not auto generated for me.

Bigger picture, I've had to stop using pkgx dev envs on most projects because of not being able to whitelist. So what happens invariably is there will be a dependency in a version file, or somewhere less clear, that pkgx does not yet provide (for example Ruby 2.x).  So I fall back to `asdf`, which uses ruby-build to try and build that version of Ruby. But since I also was using a pkgx version of Rubyas my default ruby, I would not even be able to build asdf's Ruby until I totally remove pkgx from my path. Then I could successfully build. Not sure, maybe switchers like asdf/rbenv take precautions to turn off all libs from your current asdf ruby and point instead to command line tool's versions of those libs.

Regardless, some TLDR thoughts:

* Turning off dev and unloading shell integration seems to fix many issues I was having.
* I would prefer a middle ground that would allow me to whitelist the packages I want in a pkgx dev env, thus allowing me to fall back on other package managers if need be. Pkgx's more assertive auto-load makes that difficult.
* Additionally, when trying to use with asdf, I started even seeing other issues where pkgx would also remove other non-pkgx things from the front of my path (e.g. asdf) even when I do things like cat a file (if I remember correctly). I even experienced my whole $PATH being duplicated on occasion.
* And sorry I haven't reported these bugs yet. I had to get some dev done and had to pretty much just pull out pkgx for the time being.

**Comment by mxcl** [comment]
Weird, what macOS? I have `/usr/share/terminfo` and its protected by SIP.

---

The other issues you report are super strange. Nobody else has reported anything similar since we had magic pre 1.0. We no longer have magic, everything is explicitly opt in. So if you experienced those issues post 1.0 then I am super concerned and surprised. I honestly cannot imagine how they can happen.

> I would prefer a middle ground that would allow me to whitelist the packages I want in a pkgx dev env, thus allowing me to fall back on other package managers if need be. Pkgx's more assertive auto-load makes that difficult.

Like apart from that, but well, `dev` is not configurable like that RN. Maybe it will evolve to be, but RN there are plenty of other tools or: build your own! libpkgx is the pkging primitives that make `pkgx` and `dev` possible.

**Comment by mxcl** [comment]
Should be fixed if you `pkgx --sync` then new terminal
