### ISSUE TITLE
How long does it takes for a new package published on pantry to be available?

### ISSUE THREAD

**Issue by tannevaled** [pkgxdev/pantry#3607]
Hi,

cf https://github.com/pkgxdev/pantry/actions/runs/6434426705 k3sup have been bottled but i can't get it
```bash
$ pkgx@latest +github.com/alexellis/k3sup
× nothing provides: github.com/alexellis/k3sup
│ we haven’t pkgd this yet. can you?
╰─➤ https://docs.pkgx.sh/pantry
```

Thanks.

**Comment by jhheider** [comment]
Try `pkgx --sync`. This forces a git-pull of the pantry. It _should_ be synching when it thinks the pantry might be stale, so might need to be a pkgxdev/libpkgx bug if it's not.

**Comment by tannevaled** [comment]
thanks, it solved the problem. maybe a good entry for the documentation or the pantry README?

**Comment by mxcl** [comment]
there is a bug where `pkgx` doesn't pull the pantry when it thinks it is stale which I will fix soon.

I'll add to the pantry readme that merged pkgs should be available after the amount of time it takes to rebuild them but considering most people don’t add things to the pantry it doesn't seem generally interesting to our userbase. edit: well probs should go in the pantry section of the docs too.
