### ISSUE TITLE
Need for multiple executable with brewkit python-venv.py

### ISSUE THREAD

**Issue by tannevaled** [pkgxdev/pantry#3677]
Hi.

i am packaging the openstackclient python application.
it provides two binaries: openstack and openstack-inventory.
the brewkit python-venv helper does support only one executable.

```bash
...
python-venv.py $HOME/.pkgx/opendev.org/python-openstackclient/v6.3.0/bin/openstack $HOME/.pkgx/opendev.org/python-openstackclient/v6.3.0/bin/openstack-inventory
usage: python-venv.py [-h] [--extra [EXTRA ...]] [--requirements-txt] [--no-binary] executable
python-venv: eror: unrecognized arguments: $HOME/.pkgx/opendev.org/python-openstackclient/v6.3.0/bin/openstack-inventory
$
```

```bash
$ locate python-venv.py
$HOME/.pkgx/pkgx.sh/brewkit/v0.46.4/share/brewkit/python-venv.py
```

Is it possible to modify it to accept severals?

**Comment by jhheider** [comment]
possibly this trick? https://github.com/pkgxdev/pantry/blob/main/projects/github.com/rrthomas/psutils/package.yml

but there's no reason it shouldn't be capable of linking out several binaries from a single invocation.

**Comment by tannevaled** [comment]
thanks, that trick make the job.

**Comment by mxcl** [comment]
Sorry that this isn't documented better.

Basically I don't really like our python venv hacks and want to do a better job at some point, but it's been ages so I should just admit this is how it is and document it.
