### ISSUE TITLE
Package older versions of terraform

### ISSUE THREAD

**Issue by kishaningithub** [pkgxdev/pantry#3822]
As of now, terraform versions packaged are >=1.3

Reference - https://dist.pkgx.dev/?prefix=terraform.io/darwin/aarch64

In some of my projects i would like to use older versions of terraform, specifically 0.12.x and 0.13.x

Can they be also packaged? If there can be some guidance on how to do this i can try raising a PR for the same. Thanks in advance!

**Comment by mxcl** [comment]
* 0.13 https://github.com/pkgxdev/pantry/actions/runs/6638551577
* 0.12 https://github.com/pkgxdev/pantry/actions/runs/6638565182

**Comment by mxcl** [comment]
> If there can be some guidance on how to do this i can try raising a PR for the same. Thanks in advance!

This is how you ask at this time, I think ideally people could open PRs somehow that would do it.

**Comment by jhheider** [comment]
needed some fixes. new builds are:

- 0.13 https://github.com/pkgxdev/pantry/actions/runs/6643673621
- 0.12 https://github.com/pkgxdev/pantry/actions/runs/6643673460

**Comment by kishaningithub** [comment]
Thanks a lot for the very fast response! Can the following list of terraform versions be also added? Thanks in advance! :-)

**Context**: I am working on a pretty old terraform mono repo code base with multi roots and would like to use this tool to switch between various terraform versions

```
0.11.10
0.12.0
0.12.20
0.12.24
0.12.26
0.12.31
0.12.6
0.13.4
0.13.5
0.13.7
0.14.11
0.14.5
1.0.0
1.1.0
1.1.7
1.2.9
```

**Comment by jhheider** [comment]
sent. question: is terraform using semver? because, if so, using ~x.y _should_ be sufficient, since patches should only be bug fixes, but not changes in functionality otherwise. which would reduce that list to:
```
~0.11
~0.12
~0.13
~0.14
~1.0
~1.1
~1.2
```

**Comment by jhheider** [comment]
needed some fixes for 0.14.x and 0.12.<20. 0.11.10 looks like it might be a little too old to build easily (pre-dates `go.mod`, and relies on some packages that have been renamed), but 0.11.12 builds with the above fixes. hopefully, that can work as your oldest version.

**Comment by jhheider** [comment]
```shell
$ pkg inv terraform.io
0.11.12
0.12.0
0.12.6
0.12.20
0.12.24
0.12.26
0.12.31
0.13.4
0.13.5
0.13.7
0.14.5
0.14.11
1.0.0
1.1.0
1.1.7
1.2.9
1.3.9
1.3.10
1.4.0
1.4.1
1.4.2
1.4.3
1.4.4
1.4.5
1.4.6
1.4.7
1.5.0
1.5.1
1.5.2
1.5.3
1.5.4
1.5.6
1.5.7
1.6.0
1.6.1
1.6.2
```

**Comment by kishaningithub** [comment]
Thanks a lot for doing this :-) Closing this ticket now :-)

**Comment by mxcl** [comment]
Cheers @jhheider
