### ISSUE TITLE
`pkg edit` throws error "no new package detected"

### ISSUE THREAD

**Issue by mfts** [pkgxdev/pantry#394]
Followed the steps in README
1. cloned pantry.extra
2. `cd pantry.extra`
3. `pkg init`: properly initialized a new package.yml here: `~/dev/tea/pantry.extra/projects/wip/rooibos/package.yml`
4. `pkg edit` throws the following error

```sh
$ pkg edit
~/dev/tea/pantry.extra/projects/wip/rooibos/package.yml
/usr/local/bin/code
error: no new packages in `$TEA_PANTRY_PATH`
```
 
```sh
$ echo $TEA_PANTRY_PATH
/Users/mfts/dev/tea/pantry.extra:/Users/mfts/.tea/tea.xyz/var/pantry
```

---

If I try to add `TEA_PANTRY_PATH` as a variable to `pkg edit`

```sh
$ TEA_PANTRY_PATH=/Users/mfts/dev/tea/pantry.extra pkg edit
~/dev/tea/pantry.extra/projects/wip/rooibos/package.yml
resolving package graph
~/dev/tea/pantry.extra/projects/wip/rooibos/package.yml
error: Uncaught (in promise) Error: pantry entry invalid. please report this bug!

    https://github.com/teaxyz/pantry.core/issues/new

----------------------------------------------------->> attachment begin
wip/rooibos: duplicated mapping key at line 25, column 3:
      github: user/repo/tags  # reads  ... 
      ^
<<------------------------------------------------------- attachment end
```

Seems like we are "printing" the current package path quite often.

**Comment by mxcl** [comment]
I fixed something like this today, try updating: `cd pantry.extra && tea -SE`

> Seems like we are "printing" the current package path quite often.

I don’t follow…

**Comment by mfts** [comment]
I just solved the error. I forgot to add the package name after the [brewkit](https://github.com/teaxyz/brewkit) commands. I should do `pkg edit wip/roobois` to edit the correct package.

**Comment by mxcl** [comment]
No you’re right, you don’t need to specify the pkg name. Provided it is a new file or a modified file `pkg edit` should open those pkgs in your editor

**Comment by mxcl** [comment]
I just tried

```sh
pkg init
pkg edit
```

And it opened the package for editing.

It's possible the brewkit in your main tea prefix needs updating. This is a bug which I haven't figured out a solution for yet.

```sh
cd ~ && tea --sync +tea.xyx/brewkit
```

**Comment by mfts** [comment]
ok will double check it
