### ISSUE TITLE
yt-dlp: Unknown encoder 'libmp3lame'

### ISSUE THREAD

**Issue by magnusviri** [pkgxdev/pantry#3966]
When running `yt-dlp -x --audio-format mp3 ...` I get this error.

```
ERROR: Postprocessing: audio conversion failed: Unknown encoder 'libmp3lame'
```

I tried to rebuild ffmpeg with libmp3lame like this:

```
./configure --prefix="{{prefix}}" --enable-libmp3lame
```

But I get this error.

```
ERROR: libmp3lame >= 3.98.3 not found
```

I also tried to include `lame.sourceforge.io` as an ffmpeg build dependency but it didn't fix the error. I'd try to figure this out but this is going down a rabbit hole and need to focus on something else right now. I wanted to create the issue before I forgot.

**Comment by magnusviri** [comment]
Wait, I think I'm confused. I thought yt-dlp was dependent on ffmpeg but I just double checked and I don't see it listed. I tried adding it and lame as run dependencies and that didn't fix it.

**Comment by jhheider** [comment]
above PR fixes it for me.
- add dep on ffmpeg to yt-dlp
- add dep on lame to ffmpeg
- add --enable-libmp3lame flag to ffmpeg
