### ISSUE TITLE
qrencode not working

### ISSUE THREAD

**Issue by ddobrinskiy** [pkgxdev/pantry#409]
qrencode is not working as expected: it does not generate an image

```bash
❯ qrencode 123456789 -o test.png
PNG output is disabled at compile time. No output generated.
```

Notably, while it seems to pass the CI tests, it actually fails in the same way: https://github.com/teaxyz/pantry.extra/actions/runs/4179109052/jobs/7239159814#step:8:345 

initial PR: https://github.com/teaxyz/pantry.extra/pull/393

**Comment by ddobrinskiy** [comment]
FYI @davdroman

**Comment by davdroman** [comment]
Yes sorry about this. I'm experiencing the same issue. I just had a really busy week and wasn't able to open an issue to report it. Hopefully @mxcl or @jhheider know what the cause might be.

**Comment by ddobrinskiy** [comment]
probably needs [libpng](http://www.libpng.org/pub/png/libpng.html), according to the [readme](https://github.com/fukuchi/libqrencode#requirements)

**Comment by davdroman** [comment]
The recipe does [include it](https://github.com/teaxyz/pantry.extra/pull/393/files#diff-3bfa3341b0e1a5be5a599720c963b9d277f100dec8b565024fb82b9d6f40a3ccR13) as a dependency, but I think it's not getting picked up at all by qrencode.

**Comment by davdroman** [comment]
Here's what I get on Apple M1:

```sh
$ tea qrencode 123456789 -o test.png
dyld[81328]: Library not loaded: @rpath/libpng.org/v1/lib/libpng16.16.dylib
  Referenced from: <2A2FFCCF-46E1-3BB8-B5D0-7E9F691DD14A> /Users/davdroman/.tea/fukuchi.org/qrencode/v4.1.1/bin/qrencode
  Reason: tried: '/Users/davdroman/.tea/fukuchi.org/qrencode/v4.1.1/bin/../../../../libpng.org/v1/lib/libpng16.16.dylib' (code signature in <5436BC84-99C1-35EF-9F42-19D6A7C360B9> '/Users/davdroman/.tea/libpng.org/v1.6.39/lib/libpng16.16.dylib' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)), '/Users/davdroman/.tea/fukuchi.org/qrencode/v4.1.1/bin/../../../../libpng.org/v1/lib/libpng16.16.dylib' (code signature in <5436BC84-99C1-35EF-9F42-19D6A7C360B9> '/Users/davdroman/.tea/libpng.org/v1.6.39/lib/libpng16.16.dylib' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)), '/System/Volumes/Preboot/Cryptexes/OS@rpath/libpng.org/v1/lib/libpng16.16.dylib' (no such file), '/Users/davdroman/.tea/fukuchi.org/qrencode/v4.1.1/bin/../../../../libpng.org/v1/lib/libpng16.16.dylib' (code signature in <5436BC84-99C1-35EF-9F42-19D6A7C360B9> '/Users/davdroman/.tea/libpng.org/v1.6.39/lib/libpng16.16.dylib' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)), '/Users/davdroman/.tea/fukuchi.org/qrencode/v4.1.1/bin/../../../../libpng.org/v1/lib/libpng16.16.dylib' (code signature in <5436BC84-99C1-35EF-9F42-19D6A7C360B9> '/Users/davdroman/.tea/libpng.org/v1.6.39/lib/libpng16.16.dylib' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)), '/usr/lib/libpng16.16.dylib' (no such file, not in dyld cache)
```

**Comment by jhheider** [comment]
There was a brief period where some binaries weren't getting signed. I'll trigger a rebuild of libpng. Once it's done, you should be able to delete it from ~/.tea and it'll redownload as needed.

**Comment by jhheider** [comment]
Rebuild is complete: https://github.com/teaxyz/pantry.core/actions/runs/4212686898

**Comment by davdroman** [comment]
@jhheider oh yeah, so now I'm getting the same warning as @ddobrinskiy:

```sh
$ tea qrencode 123456789 -o test.png
installed: ~/.tea/libpng.org/v1.6.39
PNG output is disabled at compile time. No output generated.
```

I think it's most likely some argument missing in the `./configure` step of the qrencode recipe, but I'm not sure what just yet. Source: https://stackoverflow.com/a/63302296/1922543

**Comment by jhheider** [comment]
Interestingly, it's clearly loading the library, if it hit the code-signing issue. I wonder if a configure flag is missing.
