### ISSUE TITLE
`npx prettier --version` reports npx version and not prettier version

### ISSUE THREAD

**Issue by mxcl** [pkgxdev/pantry#4160]
`npx prettier -- --version` works.

Apparently installing node via eg. brew the above works.

**Comment by jhheider** [comment]
```shell
#!/bin/sh

# or npx fails ※
# FIXME a patch to npm here then upstream would be preferable
mkdir -p ~/.local/lib

d="$(cd "$(dirname $0)" && pwd)"
"$d"/npm exec "$@"

# ※ https://github.com/teaxyz/cli/issues/532
```
either we should `exec` or at least use `"$d"/npm -- exec "$@"`.

**Comment by mxcl** [comment]
FACEPALM

**Comment by KubaJastrz** [comment]
LOL, I just spend 2 hours debugging this problem and landed here.

As far I noticed, this problem goes back to npm@9.0.1 in pkgx registry

**Comment by mxcl** [comment]
sorry for the issue @KubaJastrz but glad it is now solved
