### ISSUE TITLE
pipenv not working: no such file or directory: /opt/tea/pipenv.pypa.io/v2023.2.18/bin/activate

### ISSUE THREAD

**Issue by magnusviri** [pkgxdev/pantry#420]
My environment is TEA_PREFIX=/opt/tea.

```
pipenv shell
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project. You can set PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and create its own instead. You can set PIPENV_VERBOSITY=-1 to suppress this warning.
Creating a virtualenv for this project...
Pipfile: /Users/james/Dropbox/Work/jctl/jctl-pipenv/Pipfile
Using /opt/tea/pipenv.pypa.io/v2023.2.18/bin/python (3.11.1) to create virtualenv...
⠹ Creating virtual environment...created virtual environment CPython3.11.1.final.0-64 in 226ms
  creator CPython3Posix(dest=/Users/james/.local/share/virtualenvs/jctl-pipenv-Ab8-1fKZ, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/Users/james/Library/Application Support/virtualenv)
    added seed packages: certifi==2022.12.7, charset_normalizer==3.0.1, idna==3.4, importlib_metadata==6.0.0, jaraco.classes==3.2.3, jctl==1.1.19, keyring==23.13.1, more_itertools==9.0.0, pip==23.0, python_jamf==0.8.3, requests==2.28.2, setuptools==67.1.0, urllib3==1.26.14, wheel==0.38.4, zipp==3.11.0
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
...
. /opt/tea/pipenv.pypa.io/v2023.2.18/bin/activate
.: no such file or directory: /opt/tea/pipenv.pypa.io/v2023.2.18/bin/activate
```

**Comment by mxcl** [comment]
I just tried this and despite this error message it appears to work, can you re-confirm `pipenv` doesn’t work?

**Comment by magnusviri** [comment]
I've reinstalled everything and I saw the above error again, but here's an even bigger issue. The virtual environment location for everything installed is /opt/tea/pipenv.pypa.io/v2023.2.18. This goes against the whole point of pipenv. The brew version of pipenv installs everything in ~/.local/share/virtualenvs/dirname-random, where dirname is the name of the parent directory and random is some random text.

So for example, if I'm in ~/ansible and if I type `pipenv install ansible` then all of the ansible libraries and binaries will be installed in ~/.local/share/virtualenvs/ansible-dsajk42df/. Also, ~/ansible/Pipfile will be created.

Then, if I cd to ~/s3cmd and I type `pipenv install s3cmd` then all of the s3cmd libraries and binaries will be installed in ~/.local/share/virtualenvs/s3cmd-rew244cg/. Also, ~/s3cmd/Pipfile will be created.

pipenv kind of acts like npm except instead of installing everything in Node_modules it installs it in ~/.local. I don't know if that's the default behavior of pipenv or if it's how brew's pipenv is configured.

Either way, tea's pipenv is acting more like pip.

**Comment by mxcl** [comment]
probs just a configure flag to fix

**Comment by magnusviri** [comment]
I am now super confused. I just noticed that tea's pipenv did create ~/.local/share/virtualenvs/s3cmd-rew244cg/ and ~/.local/share/virtualenvs/ansible-dsajk42df/, but the libraries were installed to /opt/tea/pipenv.pypa.io/v2023.2.18.

**Comment by magnusviri** [comment]
I think (but am not sure) that it's [this line](https://github.com/teaxyz/brewkit/blob/main/share/brewkit/python-venv.sh#L15) in python-venv.sh.

**Comment by magnusviri** [comment]
Whoops, not that line. [It's this line](https://github.com/teaxyz/brewkit/blob/main/share/brewkit/python-venv.sh#L40).

**Comment by mxcl** [comment]
Seemed fixed to me, pls try the new build once it is live.

You probs have to uninstall first (`rm -rf`)

**Comment by magnusviri** [comment]
Fixed! Thanks!
