### ISSUE TITLE
`lcov` v2.0.0 can't be updated

### ISSUE THREAD

**Issue by MarkusZoppelt** [pkgxdev/pantry#4338]
`v1.16.0` works fine and is also returned as `@latest`:

```
> pkgx lcov@latest --version
lcov: LCOV version 1.16
```

<img width="550" alt="Screenshot 2023-12-07 at 11 40 49" src="https://github.com/pkgxdev/pantry/assets/2495125/6f98eec1-efd0-4fc9-b833-3f9faf957a96">

**Comment by jhheider** [comment]
lcov is `platforms: linux`. likely that changed with v2, and we _should_ have removed the 1.6.0 bottle for darwin. if we can make lcov 2 work on darwin, then we should remove the restriction in the package.yaml.
