### ISSUE TITLE
Current versions of Java (openjdk.org) and Gradle are incompatible

### ISSUE THREAD

**Issue by MarkusZoppelt** [pkgxdev/pantry#4346]
See https://docs.gradle.org/current/userguide/compatibility.html

- Latest (and only) available openjdk.org is 20 (https://dist.pkgx.dev/?prefix=openjdk.org/)
- Latest (and only) available gradle.org is 8.2.1 https://pkgx.dev/pkgs/gradle.org/

We either need an older version or openjdk.org, e.g. openjdk@17, see #662
or more recent versions of gradle.org (>= 8.3) for Java 20

**Comment by jhheider** [comment]
looks like the gradle version scanner didn't account for two-digit versions. that should be an easy fix.

openjdk can't be "fixed" as stands, because of their URL schema.

**Comment by jhheider** [comment]
gradle 8.5 should be available soon.
