### ISSUE TITLE
version request: ollama.ai

### ISSUE THREAD

**Issue by magnusviri** [pkgxdev/pantry#4436]
You only have up to 0.1.0. The latest version is 0.1.16. 0.1.15 added multimodel llava support. When I run `ollama --version` it also reports the version as 0.0.0.

**Comment by jhheider** [comment]
yep, the current doesn't build because of a bug in the brewkit v1 transition. https://github.com/pkgxdev/brewkit/pull/222 will fix it.

**Comment by jhheider** [comment]
https://github.com/pkgxdev/pantry/actions/runs/7212063053
