### ISSUE TITLE
outdated repository: github.com/charliermarsh/ruff

### ISSUE THREAD

**Issue by zanieb** [pkgxdev/pantry#4531]
This repository is now github.com/astral-sh/ruff

**Comment by jhheider** [comment]
we can certainly update the internals; @mxcl what do you think about the name? we have... [a lot of versions](https://pkgx.dev/pkgs/github.com/charliermarsh/ruff/) under the old name. maybe just a second package for confusion?

**Comment by mxcl** [comment]
we need a proper way to migrate names, but the package.yml versions key can be updated nps.

**Comment by mxcl** [comment]
The reference in the markdown is not user visible, so it seems ok to leave as is until we have some rename mechanism.

OTOH we can just have copy it to another location and remove the provides for the first entry. Add a comment saying it is copy pasta until we have a proper rename system.

**Comment by jhheider** [comment]
```yaml
renamed-to: astral.sh/ruff

# provides:
#   - bin/ruff
```

**Comment by zanieb** [comment]
Thanks!
