### ISSUE TITLE
Build older Ruby versions 2.5.x and 2.6.x

### ISSUE THREAD

**Issue by m1ch4ls** [pkgxdev/pantry#4620]
We still use 2.5.x and 2.6.x

After merging https://github.com/pkgxdev/pantry/pull/4619 the build should work.

Thank you :pray:

**Comment by jhheider** [comment]
[ruby-lang.org~2.5](https://github.com/pkgxdev/pantry/actions/runs/7351636476)
[ruby-lang.org~2.6](https://github.com/pkgxdev/pantry/actions/runs/7351636586)

**Comment by jhheider** [comment]
looks like older version don't provide `racc`, so it's failing the audit. should be an easy fix.

**Comment by jhheider** [comment]
Fix: e5624937d4263cb66413c9319e2c26fbe53682e3

[ruby-lang.org~2.5](https://github.com/pkgxdev/pantry/actions/runs/7352092246)
[ruby-lang.org~2.6](https://github.com/pkgxdev/pantry/actions/runs/7352092307)
