### ISSUE TITLE
Build older dotnet versions

### ISSUE THREAD

**Issue by MrLuje** [pkgxdev/pantry#4685]
Since `dotnet` package can now build any version (#4684), can you please build the latest version of a few major versions ?
* 7.0.404
* 6.0.417
* 5.0.408

Thanks 🙏

**Comment by jhheider** [comment]
^5: https://github.com/pkgxdev/pantry/actions/runs/7387496273
^6: https://github.com/pkgxdev/pantry/actions/runs/7387496396
^7: https://github.com/pkgxdev/pantry/actions/runs/7387496541

**Comment by jhheider** [comment]
looks like ^5 doesn't provide an SDK for darwin+aarch64:

https://dotnet.microsoft.com/en-us/download/dotnet/5.0

**Comment by MrLuje** [comment]
Ah yeah, it wasn't probably introduced before ^6 for this arch... so that's fine
Is it an issue from a manifest POV or can we leave it like that ?

**Comment by jhheider** [comment]
should be fine. you'll notice the other arches built and published. since the pkgx client looks to see what's actually bottled, it'll just be unavailable on darwin+aarch64.

**Comment by jhheider** [comment]
going to close this as completed; feel free to reopen or open a new issue if you need more versions.
