### ISSUE TITLE
+mackup

### ISSUE THREAD

**Issue by davdroman** [pkgxdev/pantry#482]
Would be good to have it, but I have no idea how to even start to write a bottle for it since it's Python based and seemingly it needs to be installed via pip.

https://github.com/lra/mackup

**Comment by jhheider** [comment]
If we're as good as we like to think, https://github.com/teaxyz/pantry.extra/blob/main/projects/pypa.github.io/pipx/package.yml probably. (if we're not, then PRs against brewkit/python-venv.sh are super welcome.)

**Comment by davdroman** [comment]
Amazingly fast turnaround! Thank you @mxcl @jhheider!
