### ISSUE TITLE
version request: openjdk.org@^17

### ISSUE THREAD

**Issue by scottjg** [pkgxdev/pantry#4829]
while working on https://github.com/pkgxdev/pantry/pull/4818, unfortunately i think the knn plugin (you need it for ai vector search) requires jdk17 to build. it seems like the existing package.yml for openjdk.org works if you replace the distribution and BOOT_JDK for the older version... but i'm not sure how to modify the distribution to list different urls for different versions. 

in this case, the current url is:
https://github.com/openjdk/jdk20u/archive/jdk-20.0.2+9.tar.gz
while the jdk17 url is:
https://github.com/openjdk/jdk17u/archive/jdk-17.0.10+6.tar.gz
so it's not _just_ the full version number that needs to be replaced

any advice?

**Comment by jhheider** [comment]
with the newest brewkit, you can now use a `transform:` key for versions: https://github.com/pkgxdev/brewkit/pull/265

that'll, combined with `{{version.tag}}` will fix the version info, but not building the BOOT_JDK URL. You might be able to do some tricks with `curl` to find the URL for a given version, but that'll take some work. unless any JDK will work (could it?) in which case maybe v19 is fine for some other versions.

i'll give it a try and see how it goes.

**Comment by jhheider** [comment]
oh, it's the repo too. hm, that's much harder, but i believe URL and versions will now take arrays, so we should be able to add that.

**Comment by scottjg** [comment]
thanks @jhheider !!

**Comment by jhheider** [comment]
np; not built yet, but we'll get it there.

**Comment by jhheider** [comment]
there we go: https://github.com/pkgxdev/pantry/actions/runs/7510735331
