### ISSUE TITLE
Something strange with gnu.org/inetutils ping

### ISSUE THREAD

**Issue by magnusviri** [pkgxdev/pantry#5065]
I'm using the pkgx ping and I've noticed something strange. When I run 2 pings at the same time, they end up pinging the same IP. I don't know if this is a problem with the original tool, or pkgx. This doesn't happen when I use the OS ping (/sbin/ping).

Here I confirm that I'm using the pkgx ping

```
which ping
/usr/local/bin/ping
```

This is the pkgx stub (/usr/local/bin/ping)

```
cat /usr/local/bin/ping
#!/bin/sh
exec pkgx +gnu.org/inetutils -- ping "$@"
```

Window 1:

```
ping 10.87.5.1
PING 10.87.5.1 (10.87.5.1): 56 data bytes
64 bytes from 10.87.5.1: icmp_seq=0 ttl=252 time=5.488 ms
64 bytes from 10.87.5.1: icmp_seq=1 ttl=252 time=4.981 ms
64 bytes from 10.87.5.1: icmp_seq=2 ttl=252 time=6.293 ms
```

Window 2:

```
ping 10.0.0.1
PING 10.0.0.1 (10.0.0.1): 56 data bytes
64 bytes from 10.87.5.1: icmp_seq=0 ttl=252 time=5.501 ms
64 bytes from 10.87.5.1: icmp_seq=1 ttl=252 time=4.988 ms
64 bytes from 10.87.5.1: icmp_seq=2 ttl=252 time=6.195 ms
```

Notice how the ping in window 2 switches to the IP of the ping in window 1? I can't fathom why this would happen.

**Comment by magnusviri** [comment]
> _🤖_
> 
> Hey there, @magnusviri! 👋 I'm [Dosu](https://dosu.dev), a bot here to help you solve bugs, answer questions, and guide you on becoming a contributor. While you're waiting for a human maintainer, think of me as your go-to for getting things moving. I'm diving into your issue with the `gnu.org/inetutils` ping oddity and will get back to you with a full answer shortly. Let's figure this out together!

Nice! LOL

One addition to add. It doesn't matter which ping I use in window 1. The ping in window 2 has to be the pkgx ping. Window 1 can be the pkgx ping or the OS ping.

**Comment by jhheider** [comment]
possibly a gnu issue; tested with homebrew's inetutils:

window 1:
```shell
$ gping 8.8.8.8
PING 8.8.8.8 (8.8.8.8): 56 data bytes
64 bytes from 8.8.8.8: icmp_seq=0 ttl=57 time=26.563 ms
64 bytes from 8.8.8.8: icmp_seq=1 ttl=57 time=25.641 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=57 time=27.243 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=57 time=25.217 ms
64 bytes from 8.8.8.8: icmp_seq=4 ttl=57 time=25.279 ms
64 bytes from 8.8.4.4: icmp_seq=0 ttl=57 time=25.893 ms (DUP!)
64 bytes from 8.8.8.8: icmp_seq=5 ttl=57 time=25.678 ms
64 bytes from 8.8.4.4: icmp_seq=1 ttl=57 time=26.860 ms (DUP!)
64 bytes from 8.8.8.8: icmp_seq=6 ttl=57 time=27.876 ms
64 bytes from 8.8.4.4: icmp_seq=2 ttl=57 time=28.339 ms (DUP!)
64 bytes from 8.8.8.8: icmp_seq=7 ttl=57 time=26.974 ms
64 bytes from 8.8.4.4: icmp_seq=3 ttl=57 time=28.691 ms (DUP!)
64 bytes from 8.8.8.8: icmp_seq=8 ttl=57 time=27.062 ms
```

window 2:
```shell
$ gping 8.8.4.4
PING 8.8.4.4 (8.8.4.4): 56 data bytes
64 bytes from 8.8.4.4: icmp_seq=0 ttl=57 time=25.894 ms
64 bytes from 8.8.8.8: icmp_seq=5 ttl=57 time=25.310 ms
64 bytes from 8.8.4.4: icmp_seq=1 ttl=57 time=26.634 ms
64 bytes from 8.8.8.8: icmp_seq=6 ttl=57 time=27.539 ms
64 bytes from 8.8.4.4: icmp_seq=2 ttl=57 time=28.418 ms
64 bytes from 8.8.8.8: icmp_seq=7 ttl=57 time=26.539 ms
64 bytes from 8.8.4.4: icmp_seq=3 ttl=57 time=28.547 ms
64 bytes from 8.8.8.8: icmp_seq=8 ttl=57 time=27.157 ms
64 bytes from 8.8.4.4: icmp_seq=4 ttl=57 time=31.270 ms
64 bytes from 8.8.8.8: icmp_seq=9 ttl=57 time=27.152 ms
```

so, i'm guessing it has to do with how GNU `ping` listens for ICMP packets.

**Comment by magnusviri** [comment]
That's weird. I will close the ticket then.
