### ISSUE TITLE
Pulumi.io doesn't work

### ISSUE THREAD

**Issue by jakobvase** [pkgxdev/pantry#5084]
```
mkdir pulumi-test && cd pulumi-test
env +pulumi.io
pulumi new typescript -y
```

Error:
```
Created project 'pulumi-test'

Please enter your desired stack name.
To create a stack in an organization, use the format <org-name>/<stack-name> (e.g. `acmecorp/dev`).
Created stack 'dev'

error: failed to load language plugin nodejs: no language plugin 'pulumi-language-nodejs' found in the workspace or on your $PATH
```

If you have pulumi installed via brew already, the commands above works, although pulumi will warn that
```
warning: using pulumi-language-nodejs from $PATH at /usr/local/bin/pulumi-language-nodejs 
```

When I read the docs about installing pulumi here: https://www.pulumi.com/docs/install/ , they write that 
```
Extract the tarball and move the binaries in the pulumi directory to a directory included in your system’s $PATH.
```

I expect that `pulumi-language-nodejs` is part of this tarball? But I don't know how to fix it.

**Comment by jhheider** [comment]
building the sdk pieces is interesting. #5087 _should_ fix that. once it's built, you should be able to `rm -rf ~/.pkgx/pulumi.io` and the new one should pull and work. hopefully. i'll ping this issue when the build is complete.

**Comment by jhheider** [comment]
ok, build is complete for everything but `linux-x86-64`. assuming you're not waiting on that ([here](https://github.com/pkgxdev/pantry/actions/runs/7746913973)), does removing and redownloading `pulumi.io` fix your issue, @jakobvase ?

**Comment by jakobvase** [comment]
It's fixed! Thanks :)

**Comment by jhheider** [comment]
great! building the sdks took a little sleuthing, but glad that fixed it.
