### ISSUE TITLE
git 2.43.0 libpsl error

### ISSUE THREAD

**Issue by kevinmichaelchen** [pkgxdev/pantry#5092]
```
/root/.pkgx/git-scm.org/v2.43.0/libexec/git-remote-http: error while loading shared libraries: libpsl.so.5: cannot open shared object file: No such file or directory
```

reverting to 2.42.1 fixes things

**Comment by jhheider** [comment]
#5094 should get it. looks like `git` links in `libpsl` if it finds it, which it now does since `curl` has required it in the latest build. just updating the `package.yml` should fix your version; i'll rebuild the others once this is done.
