### ISSUE TITLE
midnight-commander not working?

### ISSUE THREAD

**Issue by magnusviri** [pkgxdev/pantry#54]
It looks like there are 2 errors here. One is that the path is broken (/opt/midnight-comander.org instead of /opt/tea/midnight-comander.org) and the other is that it doesn't work with xterm-256color.

```
> tea -X mc
tea: installed: /opt/tea/midnight-commander.org/v4.8.28
sfs_init(): Warning: file /opt/midnight-commander.org/v4.8.28/etc/mc/sfs.ini not found
Warning: cannot open /opt/midnight-commander.org/v4.8.28/libexec/mc/extfs.d directory
Warning: cannot load codepages list
Error opening terminal: xterm-256color.

panic: split tea. we’re sorry and we’ll fix it… but you have to report the bug!

    https://github.com/teaxyz/cli/issues/new?title=panic%3Acmd+failed%3A+1%3A+%2Fopt%2Ftea%2Fmidnight-commander.org%2Fv4.8.28%2Fbin%2Fmc

----------------------------------------------------->> attachment begin
Error: cmd failed: 1: /opt/tea/midnight-commander.org/v4.8.28/bin/mc
    at run (file:///opt/tea.xyz/src/v0.16.0/src/utils/index.ts:194:34)
    at async X (file:///opt/tea.xyz/src/v0.16.0/src/app.X.ts:36:5)
    at async file:///opt/tea.xyz/src/v0.16.0/src/app.ts:34:9
<<------------------------------------------------------- attachment end
```

**Comment by jonchang** [comment]
I believe this is one of those rare cases where the package isn't relocatable by default. The shell scripts in `libexec/mc` include the absolute path to various scripts on the build machine, and it looks like tea isn't relocating those on install.

**Comment by mxcl** [comment]
The test for `mc` is:

```yaml
test:
  # FIXME: hard to test interactive tools
  script:
    mc --configure-options
```

Which is seemingly insufficient.

**Comment by magnusviri** [comment]
I just tested this and the error I have is because it isn't relocatable. It looks like you've already fixed it. But I'll wait to close this so that I remember to test it once the PR is merged.

**Comment by magnusviri** [comment]
Tested and it is fixed. Thanks!
