### ISSUE TITLE
+libcython (170/548)

### ISSUE THREAD

**Issue by mfts** [pkgxdev/pantry#543]
Formulae: https://formulae.brew.sh/formula/libcython

**Comment by and-ri** [comment]
isn't it the same? #560 
https://github.com/Homebrew/homebrew-core/blob/de8deb30cfedf8771c06647617c48aff832e00a5/Formula/cython.rb
https://github.com/Homebrew/homebrew-core/blob/de8deb30cfedf8771c06647617c48aff832e00a5/Formula/libcython.rb

**Comment by jhheider** [comment]
seems like it might be. our cython.org package doesn't provide a lib, but it seems like brew's libcython might be a python library.
