### ISSUE TITLE
maven.apache.org old versions request

### ISSUE THREAD

**Issue by felipecrs** [pkgxdev/pantry#5501]
Hi,

Would it be possible to have the following Maven versions included?

3.6.3 (latest 3.6)
3.8.8 (latest 3.8)

PS: there was no maven 3.7.

Maven 3.9 isn't backwards compatible with maven 3.6, and that's why it would be useful for some projects I build.

However, if they don't build for whatever reason, don't bother fixing them. I can do it, if I really need.

**Comment by jhheider** [comment]
~3.6: https://github.com/pkgxdev/pantry/actions/runs/8220830650
~3.8: https://github.com/pkgxdev/pantry/actions/runs/8220830671

**Comment by jhheider** [comment]
~3.6 after 81decab179eca231d7f60a3c49b7c41d922170d8: https://github.com/pkgxdev/pantry/actions/runs/8220864379

**Comment by felipecrs** [comment]
Awesome, thanks a ton!
