### ISSUE TITLE
ollama is missing its version

### ISSUE THREAD

**Issue by kjeldahl** [pkgxdev/pantry#5677]
The version needs to be set when building the package

```
pkgx ollama@latest --version
Warning: could not connect to a running Ollama instance
Warning: client version is 0.0.0
```

See https://github.com/ollama/ollama/issues/1712

Some clients are checking the version and will fail if it does not match certain criteria.

**Comment by jhheider** [comment]
thanks for the reference. should be fixed shortly.

**Comment by jhheider** [comment]
rebuilding all versions; i expect some of the older ones should fail (its evolved a lot):

https://github.com/pkgxdev/pantry/actions/runs/8391597392/job/22982419571#logs
