### ISSUE TITLE
nothing provides: android.com/cmdline-tools

### ISSUE THREAD

**Issue by and-ri** [pkgxdev/pantry#5866]
Hey :)

Can't figure out why it doesn't find `android.com/cmdline-tools` even though it's in the pantry https://pkgx.dev/pkgs/android.com/cmdline-tools/

```bash
$ pkgx +android.com/cmdline-tools
× nothing provides: android.com/cmdline-tools
│ we haven’t pkgd this yet. can you?
╰─➤ https://docs.pkgx.sh/pantry
```

**Comment by jhheider** [comment]
Hm, it works for me. I wonder if your pantry isn't synching (for any reason). Does `pkgx --sync` help?

**Comment by and-ri** [comment]
> Hm, it works for me. I wonder if your pantry isn't synching (for any reason). Does `pkgx --sync` help?

omg that helped

I should have tried this before creating an issue 😄

**Comment by jhheider** [comment]
It _should_ happen automatically, so it's still good data. I wonder why it didn't.

Glad it got you running, ArionThinker!
