### ISSUE TITLE
podman machine start (vfkit??)

### ISSUE THREAD

**Issue by tnxz** [pkgxdev/pantry#5992]
```
$ env +podman
$ podman machine start
Starting machine "podman-machine-default"
ERRO[0000] process 99955 has not ended
Error: exec: "vfkit": executable file not found in $PATH
```

**Comment by jhheider** [comment]
looks like it might need https://github.com/crc-org/vfkit; i believe it was working on darwin last time i tried. is this linux?

edit: nope, same result here; a newer requirement, perhaps.
