### ISSUE TITLE
Request for nodejs v16.13.0 on mac arm

### ISSUE THREAD

**Issue by asg0451** [pkgxdev/pantry#6015]
from error:

```
× version unavailable nodejs.org@16.13.0
│ please check the following url for available versions
│ if it’s not there, we’ll build it! open a ticket on the pantry.
╰─➤ https://dist.pkgx.dev/?prefix=nodejs.org/darwin/aarch64
```

**Comment by jhheider** [comment]
for v16 it looks like we have 16.11.1, 16.18, .19, and .20; .0 and .1.

i can trigger a build for 16.13.0.

**Comment by jhheider** [comment]
https://github.com/pkgxdev/pantry/actions/runs/8879942624

**Comment by jhheider** [comment]
Ok, this will be interesting. Because the github API can get slow for large numbers of tags, we don't slurp all of it. that version looks like it might be too far back to be reliably detected. I'll see what I can do, though this might require changes to brewkit. stay tuned.

**Comment by jhheider** [comment]
ok, easy fix. here's the run for tracking: https://github.com/pkgxdev/pantry/actions/runs/8880083985

**Comment by asg0451** [comment]
thanks!

**Comment by jhheider** [comment]
it looks like there might be issues with linux-aarch64, but that's not supremely surprising. bottles up for the other three.

**Comment by asg0451** [comment]
works great, thanks!
