### ISSUE TITLE
+github.com/fastfetch-cli/fastfetch

### ISSUE THREAD

**Issue by felipecrs** [pkgxdev/pantry#6059]
I came to know this tool today. It looks cool!

https://github.com/Homebrew/homebrew-core/blob/2a4eded9cc676fb4d54cff376a4009f22c1b5260/Formula/f/fastfetch.rb

**Comment by osalbahr** [comment]
It looks like there is a duplication (I am aware this issue is older, but has one less useful comment):

- https://github.com/pkgxdev/pantry/issues/7109
