### ISSUE TITLE
+nodejs.org@16.20.2

### ISSUE THREAD

**Issue by shotcowboystyle** [pkgxdev/pantry#6079]
Hi, thanks for the awesome project

nodejs.org@16.20.2

Please and thank you >8D

**Comment by jhheider** [comment]
https://github.com/pkgxdev/pantry/actions/runs/8990103044

**Comment by jhheider** [comment]
looks like their makefile has an issue on linux/aarch64. were you looking for that pair, @shotcowboystyle ? the other 3 builds should be available.

**Comment by shotcowboystyle** [comment]
@jhheider That got me up and running. Thanks for the quick turn around!!!
