### ISSUE TITLE
+clementtsang.github.io/bottom

### ISSUE THREAD

**Issue by felipecrs** [pkgxdev/pantry#6477]
https://clementtsang.github.io/bottom/
https://crates.io/crates/bottom
https://github.com/ClementTsang/bottom
https://formulae.brew.sh/formula/bottom

**Comment by jhheider** [comment]
way ahead of you here: https://github.com/pkgxdev/pantry/blob/main/projects/crates.io/bottom/package.yml.

2023-04-28!

**Comment by felipecrs** [comment]
lol, I was trying `pkgx bottom` instead of `pkgx btm`, my bad.
