### ISSUE TITLE
ansible-playbook --version fails

### ISSUE THREAD

**Issue by dcvz** [pkgxdev/pantry#6496]
Using the installed ansible via `pkgx` fails to run `ansible-playbook --version` and shows the following error:

```bash
ERROR: dlopen(/Users/user/.pkgx/python.org/v3.11.9/lib/python3.11/lib-dynload/_ctypes.cpython-311-darwin.so, 0x0002): Symbol not found: _ffi_type_longdouble
  Referenced from: <E3DEDBCC-9974-309F-B39A-05A64622C7B9> /Users/dcvz/.pkgx/python.org/v3.11.9/lib/python3.11/lib-dynload/_ctypes.cpython-311-darwin.so
  Expected in:     <339C15B2-234E-3951-989C-A5721ABE49A8> /Users/dcvz/.pkgx/sourceware.org/libffi/v3.4.4/lib/libffi.8.dylib
```

interestingly the pkgx website does not show python as a dependency

**Comment by jhheider** [comment]
Looks like ansible was converted to `bkpyvenv` build (which removes python as a dependency by building the venv more correctly). `rm -rf ~/.pkgx/ansible.com; pkgx +ansible.com@latest` _should_ fix it.

**Comment by jhheider** [comment]
closing this; reopen if still needed.
