### ISSUE TITLE
+zathura

### ISSUE THREAD

**Issue by tnxz** [pkgxdev/pantry#6534]
[https://pwmt.org/projects/zathura/](https://pwmt.org/projects/zathura/)

**Comment by jhheider** [comment]
simple enough: https://github.com/zegervdv/homebrew-zathura/blob/master/Formula/zathura.rb

https://github.com/pwmt/zathura

will need their library, `girara`: https://github.com/pwmt/girara; i think the other reqs are probably done already.

**Comment by jhheider** [comment]
looks like it'll need some plugins to do anything, but i've got the interface built and running using gtk3.

https://pwmt.org/projects/zathura/plugins/
