### ISSUE TITLE
+pyenv-virtualenv (421/548)

### ISSUE THREAD

**Issue by mfts** [pkgxdev/pantry#675]
Formulae: https://formulae.brew.sh/formula/pyenv-virtualenv

**Comment by jylin** [comment]
This doesn't seem to work. If you run "virtualenv" it errors:
`RuntimeError: failed to detect cpython3.11.2-64|cpython3.11.2|cpython3.11-64|cpython3.11|cpython3-64|cpython3|cpython-64|cpython|python3.11.2-64|python3.11.2|python3.11-64|python3.11|python3-64|python3|python-64|python in /Users/aa/.tea/python.org/v3.11.2`

**Comment by jylin** [comment]
https://github.com/pypa/virtualenv/issues/2533#issuecomment-1492024529

**Comment by jhheider** [comment]
https://github.com/teaxyz/pantry/pull/419
