### ISSUE TITLE
Build latest versions of `opentofu` (currently 1.7.x)

### ISSUE THREAD

**Issue by bdruth** [pkgxdev/pantry#6753]
Currently, `+tofu` installs `1.6.0-dev` of opentofu, but the latest release is 1.7.3, as of this writing. There's a syntax change in this version that's not backwards compatible (endpoint vs endpoints), so HCL written against 1.7.x isn't working on 1.6.x.

Thanks!

**Comment by jhheider** [comment]
yep, looks like it was hardcoded to use 1.6.0-alpha3 because it was packaged before there were any releases. easy fix!

**Comment by jhheider** [comment]
our darwin/x86-64 is a little backed up because open-mpi takes ~4-5 hours to build, but once the others pass CI I'll merge, and they should build faster. so, 1.7.3 should be available for everything but darwin/x86-64 soon, and the latter by tomorrow.
