### ISSUE TITLE
+Apptainer

### ISSUE THREAD

**Issue by gapplef** [pkgxdev/pantry#6861]
Apptainer is a container system designed for ease-of-use on shared systems and in HPC environments.
Apptainer was formerly known as Singularity and is now [a part of the Linux Foundation](https://apptainer.org/news/community-announcement-20211130).

https://github.com/apptainer/apptainer

https://apptainer.org/

**Comment by gapplef** [comment]
Thanks a lot for your quick fix! 👍  🎉

**Comment by jhheider** [comment]
no problem!
