### ISSUE TITLE
govulncheck needs a rebuild for go 1.23

### ISSUE THREAD

**Issue by kevinmichaelchen** [pkgxdev/pantry#7041]
Just upgraded a personal project from Go 1.22 to 1.23, and we're seeing the error below.

I think we just need to rebuild the [**`govulncheck` pantry**](https://github.com/pkgxdev/pantry/blob/main/projects/go.dev/govulncheck/package.yml#L13) on a newer version of Go?

```
govulncheck: Loading packages failed, possibly due to a mismatch between the Go version
used to build govulncheck and the Go version on PATH. Consider rebuilding
govulncheck with the current Go version.

-: This application uses version go1.22 of the source-processing packages but runs version go1.23 of 'go list'. It may fail to process source files that rely on newer language features. If so, rebuild the application using a newer version of Go.
```

**Comment by jhheider** [comment]
interesting. that's easily done. hopefully it's backwards compatible (since it's not forwards compatible).
