### ISSUE TITLE
yt-dlp

### ISSUE THREAD

**Issue by ghost** [pkgxdev/pantry#71]
Gives this error when building: 
error: parser: pantry: package.yml (spilt-tea-102)
pantry entry invalid. please report this bug!

    https://github.com/teaxyz/pantry.core/issues/new

package.yml:

distributable:
  url: https://github.com/yt-dlp/yt-dlp/archive/refs/tags/{{version}}.tar.gz
  strip-components: 1

versions:
  github: yt-dlp/yt-dlp/tags

build:
  dependencies:
    python.org: 3
  script:
    make

test:
  script: true

**Comment by magnusviri** [comment]
It's dependent on another pull request. See the last comment here: https://github.com/teaxyz/pantry.extra/pull/45

**Comment by ghost** [comment]
oh should have checked thank you!!
