### ISSUE TITLE
+fastfetch

### ISSUE THREAD

**Issue by i-api** [pkgxdev/pantry#7109]
https://github.com/fastfetch-cli/fastfetch

**Comment by jhheider** [comment]
yeah, a good option; based on https://github.com/Homebrew/homebrew-core/blob/c3c5be2ae7ceef7b5b690a1dae9ab02fc1c9d0c2/Formula/f/fastfetch.rb, it looks like we'd need to add:
- chafa
- ddcutil
- libdrm
- opencl-icd-loader
- pulseaudio (this one potentially large)
- rpm

**Comment by felipecrs** [comment]
I don't think all these are necessary. Perhaps we can just start small.

https://github.com/fastfetch-cli/fastfetch/wiki/Building

They state dependencies are not mandatory. If they are not found, the data will simply not be shown in fastfetch when invoked.
