### ISSUE TITLE
version request: moonrepo.dev/moon 1.25.4

### ISSUE THREAD

**Issue by iyefrat** [pkgxdev/pantry#7247]
This is the version I'm actively using at the moment, I'd like to start using pkgx immediately to install moon

**Comment by jhheider** [comment]
https://github.com/pkgxdev/pantry/actions/runs/10833283929

**Comment by iyefrat** [comment]
thank you!

**Comment by jhheider** [comment]
looks like repo format changed since then. PR going up momentarily.

**Comment by jhheider** [comment]
https://github.com/pkgxdev/pantry/actions/runs/10833547655

**Comment by iyefrat** [comment]
Thank you for the quick fix! I can confirm that it works on my end
