### ISSUE TITLE
+alacritty

### ISSUE THREAD

**Issue by clanghans** [pkgxdev/pantry#7363]
Hi, 

have tried to package alacritty and created a PR with #7362 but somehow I can't get it to work on *Nix.

Also I can't find the solution to 
``` 
error: Uncaught (in promise) Error: ambiguous pkg spec
      if (rest.length) throw new Error("ambiguous pkg spec")
```
Any help would be appreciated.

**Comment by jhheider** [comment]
Couple of easy fixes. Thanks for the contribution!
