### ISSUE TITLE
nx.dev only works with node v18

### ISSUE THREAD

**Issue by sporkd** [pkgxdev/pantry#7429]
I'm getting the following intersect error when I try to run `nx.dev` on any version of node other than 18:

```
❯ dev              
× unexpected error cannot intersect: ^18 && ^20
│ Error: cannot intersect: ^18 && ^20
```

This seems too restrictive since I can `npm install nx` with nodes > 18
https://github.com/pkgxdev/pantry/blob/main/projects/nx.dev/package.yml#L15

**Comment by jhheider** [comment]
probably a remnant of when it wasn't v19 ready. should be able to separate the build/runtime versions.

**Comment by jhheider** [comment]
that change is pushed; if it's still misbehaving, a `pkgx --sync` should pull it in.

**Comment by sporkd** [comment]
Thank you @jhheider! Working now 💯
