### ISSUE TITLE
tea can't rebuild itself (using `new-version`), because it deletes itself before the script begins

### ISSUE THREAD

**Issue by jhheider** [pkgxdev/pantry#763]
^title. teaxyz/setup makes /opt/tea.xyz/vx.y.z/bin/tea, and rebuilding vx.y.z deletes it first thing. a possible workaround might be to install tea using the sh <(curl tea.xyz) at the beginning of the script.

**Comment by mxcl** [comment]
we could install tea to foo and then build to bar.

**Comment by jhheider** [comment]
Possibly the right way is just not to remove target directory on build for `tea.xyz`. Since it's a single bin, it'll just live there until it's overwritten by the new build.

**Comment by mxcl** [comment]
Fixed with BrewKit v1
