### ISSUE TITLE
Consolidate build failure tickets

### ISSUE THREAD

**Issue by mxcl** [pkgxdev/pantry#768]
One per package pls.

I know this significantly complicates it. But we must avoid overloading ourselves with noise.

**Comment by mxcl** [comment]
Well ok I guess that's not necessarily good. Let's discuss.

**Comment by jhheider** [comment]
I think it's possible. Just need to find and update the issue. Let's leave this open.

**Comment by mxcl** [comment]
what we want is “one ticket per set of new build failures”. Not sure if there's a simple way to do that other than “one ticket per project”
