### ISSUE TITLE
pkgx installation of spotify_player doesn't show album art image

### ISSUE THREAD

**Issue by i-api** [pkgxdev/pantry#7715]
<img width="1074" alt="1" src="https://github.com/user-attachments/assets/4bec171a-b347-44a8-bc12-d91174b03989">
spotify_player installed via homebrew version shows the album image art fine ^

<img width="1075" alt="2" src="https://github.com/user-attachments/assets/f5d9fcb5-71de-44de-a244-7cf36681c78e">
spotify_player installed via pkgx fails to show the album image art

**Comment by jhheider** [comment]
possibly a build feature or required dependency.

**Comment by jhheider** [comment]
https://github.com/aome510/spotify-player?tab=readme-ov-file#image

**Comment by jhheider** [comment]
Once https://github.com/pkgxdev/pantry/actions/runs/11506124229 finishes, `rm -rf ~/.pkgx/crates.io/spotify_player && pkgx +crates.io/spotify_player` should get the updated builds. I enabled most compatible features.
