### ISSUE TITLE
venv: error while loading shared libraries: libpython3.11.so.1.0 

### ISSUE THREAD

**Issue by igorgatis** [pkgxdev/pantry#7733]
Repro steps:
```sh
docker run -it --rm pkgxdev/pkgx:v1.2.2 /bin/bash
```
Then:
```sh
pkgx install python@3.11
pkgx python@3.11 -m venv .venv
source .venv/bin/activate
python -m pip install poetry==1.8.3
```

Here is an output example:
```
$ docker run -it --rm pkgxdev/pkgx:v1.2.2 /bin/bash
pkgx/ $ pkgx install python@3.11
pkgx: installed: /usr/local/bin/python
pkgx/ $ pkgx python@3.11 -m venv .venv
 ✓  ~/.pkgx/libpng.org/v1.6.44
 ✓  ~/.pkgx/x.org/util-macros/v1.20.1
 ✓  ~/.pkgx/sourceware.org/bzip2/v1.0.8
 ✓  ~/.pkgx/freedesktop.org/pkg-config/v0.29.2
 ✓  ~/.pkgx/x.org/xdmcp/v1.1.5
 ✓  ~/.pkgx/curl.se/ca-certs/v2024.9.24
 ✓  ~/.pkgx/bytereef.org/mpdecimal/v2.5.1
 ✓  ~/.pkgx/sourceware.org/libffi/v3.4.6
 ✓  ~/.pkgx/x.org/xau/v1.0.11
 ✓  ~/.pkgx/x.org/protocol/v2024.1.0
 ✓  ~/.pkgx/x.org/exts/v1.3.6
 ✓  ~/.pkgx/freetype.org/v2.13.3
 ✓  ~/.pkgx/libexpat.github.io/v2.6.3
 ✓  ~/.pkgx/tukaani.org/xz/v5.6.3
 ✓  ~/.pkgx/x.org/xcb/v1.17.0
 ✓  ~/.pkgx/pip.pypa.io/v24.3.1
 ✓  ~/.pkgx/openssl.org/v1.1.1w
 ✓  ~/.pkgx/tcl-lang.org/v8.6.15
 ✓  ~/.pkgx/x.org/x11/v1.8.10
 ✓  ~/.pkgx/pkgx.sh/v1.2.2
 ✓  ~/.pkgx/python.org/v3.11.10
pkgx/ $ source .venv/bin/activate
(.venv) pkgx/ $ python -m pip install poetry==1.8.3
python: error while loading shared libraries: libpython3.11.so.1.0: cannot open shared object file: No such file or directory
```

**Comment by jhheider** [comment]
This looks like an issue with `pkgx install`. Does `pkgx python~3.11 -m pip install poetry==1.8.3` work correctly?

**Comment by igorgatis** [comment]
It does work in the sense it does not crash. However, the package gets installed outside the virtual environment. In fact, the the newly created venv is unusable for any practical purpose.

**Comment by jhheider** [comment]
ah, right. yes, as i recall there's some weirdness with loading a venv over a dev env, with it overwriting things from the pkgx env. @sanchitram1 you've done a lot of python venv stuff (although mostly on darwin). have you encountered this?

my guess is venv is crushing the LD_LIBRARY_PATH needed to find libpython3.11.so.1.0. this can be solved (manually) with symlinks and the like, but something better would be better.

**Comment by igorgatis** [comment]
What if it was statically linked? Say, remove this line: https://github.com/pkgxdev/pantry/blob/1559436a6e3ca6ef1e96cf994834081212804218/projects/python.org/package.yml#L215

**Comment by jhheider** [comment]
it's certainly worth a try. it looks like homebrew dynamically links their python on linux, but they generally have fixed paths, whereas our binaries are relocatable. if you want to try it locally, it's just a matter of commenting out that line and doing a `bk build python.org~3.11` in a pantry check out. i'm sure there's a few other packages that would need rebuilding, but it should simplify things otherwise.

it looks like the following packages have tricks to bring in libpython:

- ansible.com
- mesonbuild.com
- pipenv.pypa.io
- virtualenv.pypa.io

Edit: testing this now

**Comment by jhheider** [comment]
that does seem to fix the issue. i'm going to check some of those 4 to see if they have issues, but that seems like a reasonable fix.

**Comment by jhheider** [comment]
looking good. i'll push it and rebuild our python packages. once that's done, you'll need to `rm -rf ~/.pkgx/python.org` to refetch them.

**Comment by igorgatis** [comment]
FWIW, running `python` does work. But the original command `python -m pip install poetry==1.8.3` doesn't. It fails with:
```
...
ImportError: libexpat.so.1: cannot open shared object file: No such file or directory
```

I guess there is not easy way around the need for `LD_LIBRARY_PATH` in `.venv/bin/activate`. I noticed that `pkgx +python@3.11` prints the following list of env vars:
```
SSL_CERT_FILE
TERMINFO_DIRS
XDG_DATA_DIRS
PKG_CONFIG_PATH
CPATH
LIBRARY_PATH
MANPATH
PATH
LD_LIBRARY_PATH
```
Where do those get generated/set?

**Comment by jhheider** [comment]
> Where do those get generated/set?

here, basically: https://github.com/pkgxdev/libpkgx/blob/fd014439204460453e1f77fe7d009d5b4ec164b7/src/hooks/useShellEnv.ts#L35-L113

the problem is layering environment managers. one (awkward) option is to add something like `source <(pkgx +python~3.11)` to `venv/bin/activate`, but that doesn't feel great.

**Comment by igorgatis** [comment]
BTW, sounds like better venv checking would be:
```
     # check to see if we can create a venv
     # we can't ensurepip on 3.7 so, this won't work
-    - run: python -m venv myvenv
+    - run: |
+        python -m venv myvenv
+        myvenv/bin/python --version
+        myvenv/bin/python -c "import zlib"
+        myvenv/bin/python -c "import pyexpat"
+        source myvenv/bin/activate
+        deactivate
```
