### ISSUE TITLE
:duck:  +duckdb

### ISSUE THREAD

**Issue by adriens** [pkgxdev/pantry#780]
:thought_balloon: Not sure if it should be implemted from source (`cmake`) or [from existing `brew` formulae](https://formulae.brew.sh/formula/duckdb)

# :ticket: Related content

- https://github.com/duckdb/duckdb/discussions/6721
- https://formulae.brew.sh/formula/duckdb

**Comment by mxcl** [comment]
quack

**Comment by adriens** [comment]
OMG, already ?!!!

**Comment by adriens** [comment]
AH AH AH

```shell
tea duckdb | duckdb -c 'select version();'
```

![image](https://user-images.githubusercontent.com/5235127/225493333-817cf2cc-9d3b-49c6-8fb7-5913108c7918.png)

**Comment by adriens** [comment]
Yes, but something odd : 

- https://github.com/teaxyz/pantry.extra/issues/787

**Comment by adriens** [comment]
- https://github.com/duckdb/duckdb-web/pull/642

**Comment by adriens** [comment]
- https://github.com/duckdb/duckdb/discussions/6721#discussioncomment-5339140

**Comment by adriens** [comment]
:point_right:   [DuckDb on tea.xyz :tea:](https://youtu.be/A3-CXrOEumM)
