### ISSUE TITLE
:duck: Bad version for duckdb :lady_beetle: 

### ISSUE THREAD

**Issue by adriens** [pkgxdev/pantry#787]
Versions are not matching : 

![image](https://user-images.githubusercontent.com/5235127/225500197-00ad809a-7ad2-4f07-b8f6-9c281a247355.png)

**Comment by mxcl** [comment]
it compiled its version in via a git tag. Fixed

**Comment by adriens** [comment]
Unit tests below on a fresh linux Ubuntu playground on Killercoda : 

```shell
uname -a
cat /etc/issue
sh <(curl https://tea.xyz) +duckdb.org duckdb -version
```

![image](https://user-images.githubusercontent.com/5235127/225753220-ce545878-1906-4c35-a1d8-335fb116a958.png)


```shell
uname -a
cat /etc/issue
sh <(curl https://tea.xyz) +duckdb.org duckdb -c 'select version()'
```

![image](https://user-images.githubusercontent.com/5235127/225753689-d8a36b5a-02e1-4639-997e-ce1d23efd1d0.png)

**Comment by adriens** [comment]
:pray: :clap:

**Comment by adriens** [comment]
:crossed_fingers:
