### ISSUE TITLE
:heavy_plus_sign:  kaggle (from pypi) :scientist: 

### ISSUE THREAD

**Issue by adriens** [pkgxdev/pantry#788]
https://pypi.org/project/kaggle/

```shell
pip install kaggle
```

**Comment by mxcl** [comment]
Should be pretty simple, check out https://github.com/teaxyz/pantry/blob/main/projects/pygments.org/package.yml for an example of how to pkg a python project

**Comment by magnusviri** [comment]
The github repo isn't using releases or tags. We could install from [pypi.org](https://pypi.org/project/kaggle/#history), which is versioned. Or we could install by calver or hash. I haven't looked into that yet.

**Comment by mxcl** [comment]
If they aren't versioning on GitHub then this is not our bag.

My goal is for typing `kaggle foo` to do `pipx kaggle foo` so maybe let’s wait for that.
