### ISSUE TITLE
+stable-diffusion-webui

### ISSUE THREAD

**Issue by magnusviri** [pkgxdev/pantry#794]
There is this text in README.

```
 git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui
$ tea \
  --cd stable-diffusion-webui \
  +python.org~3.10 +pip.pypa.io +gnu.org/wget +protobuf.dev +rust-lang.org \
  ./webui.sh
```

I would like to actually turn this into a project that lives in ~/.tea/github.com/automatic1111/stable-diffusion-webui. Part of what I'd like to do is put the models in ~/.tea/, maybe a directory like huggingface.co or stability.ai. And I'd like to put the output files either in the cwd or something specified. Something like this.

**Comment by mxcl** [comment]
one reason I didn't pkg sd-webui is they don't have releases.

But maybe we just need to figure out how to go about that. We have a few pkgs that have no releases already.

**Comment by mxcl** [comment]
> Part of what I'd like to do is put the models in ~/.tea

pkg’d or not pkg’d?

If not pkg’d then I already looked into this and specifying the model directory is pretty easy.

**Comment by magnusviri** [comment]
> one reason I didn't pkg sd-webui is they don't have releases.

I thought I saw releases, but you're right. I could ask them to make releases.

I forgot that we aren't supposed to distribute the model files. Everyone is supposed to create a huggingface account and create an API token to download it via the command line.

**Comment by magnusviri** [comment]
This is packaged.

**Comment by mxcl** [comment]
> Everyone is supposed to create a huggingface account and create an API token to download it via the command line.

We can totally have the gui streamline this. Button to log-in and get API token or something.
