### ISSUE TITLE
Not able to download `SwiftLint` on Linux

### ISSUE THREAD

**Issue by waliid** [pkgxdev/pantry#8059]
Hi guys, Hi @jhheider,

I'm trying to figure this **download failure** issue. Do you have any ideas?

![Screenshot 2024-11-29 at 19 34 20](https://github.com/user-attachments/assets/bd745ed8-7af8-4482-bebe-cee02f240eba)

**Comment by jhheider** [comment]
the vendored binary is for x86-64: https://github.com/realm/SwiftLint/releases/tag/0.57.1.

to build for aarch64, if possible, we'd have to get a working swift toolchain and build from source. if you're using it in docker (as it potentially appears above), you can use the `--platform linux/amd64` to emulate x86-64 at a slight performance penalty.
