### ISSUE TITLE
:heavy_plus_sign: gomplate (go.mod)

### ISSUE THREAD

**Issue by adriens** [pkgxdev/pantry#817]
cf https://github.com/hairyhenderson/gomplate

**Comment by adriens** [comment]
- https://github.com/hairyhenderson/gomplate/pull/1700

**Comment by adriens** [comment]
[:gift_heart: ☕ Make software packaging... a cup of tea.xyz ](https://dev.to/adriens/make-software-packaging-a-cup-of-teaxyz-3h77) :pray: @mxcl

**Comment by mxcl** [comment]
@adriens great article! We should add this to a wiki section

**Comment by adriens** [comment]
> We should add this to a wiki section

That would definitely a great section to add : contributors could add some dedicated usage scenarios :bulb:
