### ISSUE TITLE
Documentation in Wiki is linking to some old dead links

### ISSUE THREAD

**Issue by hisaac** [pkgxdev/pantry#822]
Hey there! I noticed that some of the links on [this page of the wiki](https://github.com/teaxyz/pantry/wiki) link to some outdated URLs. Specifically, they're using `pantry.zero` in the URL, when it should just be `pantry`.

Current:

```text
https://github.com/teaxyz/pantry.zero/wiki/Packaging-Guide
```

Should be:

```text
https://github.com/teaxyz/pantry/wiki/Packaging-Guide
```

**Comment by mfts** [comment]
Yes the wiki is outdated. We moved most of the docs to https://docs.tea.xyz. 

However I will go through the wiki and update it where necessary.

**Comment by hisaac** [comment]
Ah! I didn't realize the documentation had moved. Thank you.
