### ISSUE TITLE
llama.cpp convert.py does not work

### ISSUE THREAD

**Issue by magnusviri** [pkgxdev/pantry#8273]
The llama.cpp project file [says](https://github.com/pkgxdev/pantry/blob/fbed0906c6c4ea6719895039e6b9b87f73d09b99/projects/github.com/ggerganov/llama.cpp/package.yml#L15C9-L15C56):

```
# NOTE! we do not “provide” convert.py. ∵ it’s too generic
# do `pkgx +github.com∕ggerganov∕llama.cpp convert.py`
```

Note: the yaml file (quoted above) is using "∕" instead of "/". The line below is using the correct slash.

Running `pkgx +github.com/ggerganov/llama.cpp convert.py` produces:

```
× nothing provides: github.com/ggerganov/llama.cpp
│ we haven’t pkgd this yet. can you?
╰─➤ https://docs.pkgx.sh/pantry
```

I tried running `pkgx +github.com/ggerganov/llama.cpp zsh` and then `convert.py` and I get this error:

```
  File "/opt/pkgx/github.com/ggerganov/llama.cpp/v2740.0.0/venv/bin/convert.py", line 28, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
```

So convert.py (/opt/pkgx/github.com/ggerganov/llama.cpp/v2740.0.0/bin/convert.py) launches /opt/pkgx/github.com/ggerganov/llama.cpp/v2740.0.0/venv/bin/convert.py and the top of that file is `#!/usr/bin/env python3`. The correct path of python is `/opt/pkgx/github.com/ggerganov/llama.cpp/v2740.0.0/venv/bin/python`, which parent directory is not in the PATH var and so `/usr/bin/env python3` does not return that path.

I modified bin/convert.py (not venv/bin/convert.py) and changed the last line from:

```
os.execv(arg0, args)
```

to

```
args.insert(0, python_symlink)
os.execv(python_symlink, args)
```

and it works.

**Comment by magnusviri** [comment]
Note, after changing /opt/pkgx/github.com/ggerganov/llama.cpp/v2740.0.0/bin/convert.py then this works:

```
pkgx +github.com/ggerganov/llama.cpp zsh
convert.py
```

This still doesn't work:

```
pkgx +github.com/ggerganov/llama.cpp convert.py
```

**Comment by jhheider** [comment]
looks like we should probably just add it to the provides. that then leaves us with the numpy issue, so we probably need to install it manually around line 116 of the package.yml

**Comment by jhheider** [comment]
very strange. numpy is certainly there, but it's failing that (the other imports are all passing). so there's a Strange Python Thing™ happening.

**Comment by magnusviri** [comment]
Python uses the path to itself (argv[0]) to decide where to look for installed libraries. It's all relative to argv[0]. The convert.py script can't find the installed numpy because it is using the wrong python binary path.

The top of /opt/pkgx/github.com/ggerganov/llama.cpp/v2740.0.0/venv/bin/convert.py has `#!/usr/bin/env python3`, which does not return the correct path because `/opt/pkgx/github.com/ggerganov/llama.cpp/v2740.0.0/venv/bin/` is not in the PATH var. So `/usr/bin/env python3` returns the wrong python binary path.

So you either need to add `/opt/pkgx/github.com/ggerganov/llama.cpp/v2740.0.0/venv/bin/` to the PATH var or you need to change `#!/usr/bin/env python3` to `#!/opt/pkgx/github.com/ggerganov/llama.cpp/v2740.0.0/venv/bin/python`.

**Comment by jhheider** [comment]
ah, gotcha. hm. i wonder if it'll take a relative path. `#!./python` *might* work.

**Comment by jhheider** [comment]
the above fix works for me. I'm not going to rebuild 1,800 versions (lord. obviously.) but if there's a specific version you need prior to `b4390`, just let me know and I'm happy to rebuild it.

**Comment by magnusviri** [comment]
Sounds good to me. I don't need older versions.
