### ISSUE TITLE
github.com/util-linux/util-linux for macOS?

### ISSUE THREAD

**Issue by magnusviri** [pkgxdev/pantry#831]
The [Homebrew version](https://github.com/Homebrew/homebrew-core/blob/0e4a4aa7a071151b00fb51551892546e94e2b77a/Formula/gnu-getopt.rb) of [github.com/util-linux/util-linux](https://github.com/teaxyz/pantry/blob/main/projects/github.com/util-linux/util-linux/package.yml) works on macOS. Is there a plan to get the tea version to work on macOS? I need it for xmlto, which I need for wumpus.

**Comment by mxcl** [comment]
brew only build `getopt` out of that [by the look of it][by]

[by]: https://github.com/Homebrew/homebrew-core/blob/0e4a4aa7a071151b00fb51551892546e94e2b77a/Formula/gnu-getopt.rb#L42

**Comment by mxcl** [comment]
k MacPorts have a patch to make it build: https://github.com/macports/macports-ports/blob/master/devel/util-linux/Portfile

**Comment by mxcl** [comment]
k requires an adjustment to tea/cli before this will work
