### ISSUE TITLE
code signing breaks hardlinks

### ISSUE THREAD

**Issue by mxcl** [pkgxdev/pantry#896]
fix-macho.rb goes to good lengths to ensure that hard links are not breaking by code signing.

The new code signing stuff doesn't do this. As a result git’s pkg is 10× the size it could be.

**Comment by mxcl** [comment]
not urgent

**Comment by jhheider** [comment]
Maybe fix-machos should just take an optional signing identity.

**Comment by jhheider** [comment]
I wonder how badly `git` would break if we just relinked it all as symlinks...

**Comment by mxcl** [comment]
> Maybe fix-machos should just take an optional signing identity.

This is fine and frankly probably what we should have done in the first place. fix-macho should be checking everything that needs codesigning

**Comment by jhheider** [comment]
PRs ready. https://github.com/webiny/action-post-run came in handy. Fairly clean, but I did have to borrow and modify the Machos.codesign! function out of ruby-machos to inject our logic into it. It's short enough, anyway.
