### ISSUE TITLE
+lunarvim.org

### ISSUE THREAD

**Issue by hinogi** [pkgxdev/pantry#94]
https://www.lunarvim.org/
tea +python.org +rust-lang.org +neovim.io
LV_BRANCH='release-1.2/neovim-0.8' bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh)

Installation of Rust dependencies: fd::fd-find, rg::ripgrep doesn't seem to work due to some unknown dependencies but the rest should work.

**Comment by mxcl** [comment]
Weird they don't have build instructions. I was going to jump in. The install script is a little hard to decode.

We possibly could just run the install script in the `package.yml`, but we prefer well defined build steps. Now possibly they don't provide them because they intend to change the instructions regularly?

**Comment by hinogi** [comment]
@LostNeophyte is currently working on making it more accessible that's why I closed it :D currently it would also need gcc which is also in the making

**Comment by mxcl** [comment]
oh ok. Well we'll leave this open if you're cool with that. I want all the things!

**Comment by LostInTheLogs** [comment]
> Now possibly they don't provide them because they intend to change the instructions regularly?

Packaging was added very recently, it's in beta

> I was going to jump in. The install script is a little hard to decode. We possibly could just run the install script in the `package.yml`, but we prefer well defined build steps. 

Here's some info that should help:

You can now use `cmake` from https://github.com/LunarVim/LunarVim-mono to build and install lunarvim (our packaging repo is separate from the code)

take a look at our [packaging github workflow](https://github.com/LunarVim/LunarVim-mono/blob/master/.github/workflows/release.yml) for usage examples

the build generates a `lvim` bash script used to start lunarvim, `version.txt` with our version string: `git_branch/git_commit` and `sem_version.txt` with a semantic version. It will build the master branch (nightly version) of LunarVim/LunarVim by default, I haven't figured out how to do actual releases yet

build dependencies:
- cmake
- git
- bash
- neovim (optional, but nice to have, use `-DBUNDLE_PLUGINS=0` if you don't want the build to use it)

runtime dependencies:
- neovim
- bash
- C compiler
- ripgrep (optional, most people would want it)
- fd-find (optional, most people would want it)

**Comment by LostInTheLogs** [comment]
you can now set LVIM_VERSION as an env or cmake variable to build a specific version, valid values are the the tags from [LunarVim/LunarVim](https://github.com/LunarVim/LunarVim), but the tag needs to be > 1.2.0 (currently there are no such tags)
